### ISSUE TITLE
Need to fix the S3 inconsistency of the `check_night` function

### ISSUE THREAD

**Issue by stijnvanhoey** [adokter/bioRad#100]
checking S3 generic/method consistency ... WARNING
```
check_night:
  function(x, ..., elev)
check_night.default:
  function(lon, lat, date, elev)
```

should be having the same arguments, see http://www.hep.by/gnu/r-patched/r-exts/R-exts_152.html

**Comment by adokter** [comment]
No longer get this warning message when running devtools::check(), closing
