### ISSUE TITLE
Reference list contains some odd functions

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#109]
The [new reference list](https://rawgit.com/adokter/bioRad/c17d0e51103d67131385b0018687276a2cd9becf/docs/reference/index.html) contains some functions that should not be there:

- [x] `get_suntime`: Helper function to calculate sunrise or sunset
- [x] `proj_to_wgs`: A wrapper for spTransform.
- [x] `read_vp`: Read a vertical profile (vp) from file
- [x] `vplist_to_vpts`: Bind vertical profiles (vp) into time series (vpts)
- [x] `wgs_to_proj`: A wrapper for spTransform.
- [x] `bioRad-package`: Analyze and visualize biological signals in weather radar data

I have no idea why, but I left the reference list as an automatic reference list (not manually sectioned), so it is possible to update function aspects and do `pkgdown::build_reference_index()` to see if it affects anything.

**Comment by peterdesmet** [comment]
Preview of the website available at https://rawgit.com/adokter/bioRad/c17d0e51103d67131385b0018687276a2cd9becf/docs/index.html

**Comment by adokter** [comment]
I think this will be fixed by commit e1292ad0fbe2d0d9e0a90a9ad77a428819ba7df4

Note that `bioRad-package` should not be hidden, as you should always be able to pull up a help page called <package-name>-package according to R conventions

**Comment by stijnvanhoey** [comment]
@adokter, @peterdesmet, for internal functions the handle `@noRd` seems another [option](http://style.tidyverse.org/code-documentation.html#internal-functions). As this will exclude `Rd` pages to be made, the pgkdown package won't use it as well. `@keywords internal` will make an Rd` page, but won't show it to the end-user.

**Comment by adokter** [comment]
Hi @stijnvanhoey,

`bioRad-package` is the package main page, that one we should keep for sure (all packages have a PackageName-package file, it comes up when you do ?PackageName

I would prefer suppressing the documentation of the other internal function as well, so please proceed

**Comment by peterdesmet** [comment]
We now use `@keywords internal` for internal functions, allowing user to still do e.g. `? proj_to_wgs()` and having these functions **not** show up in reference list (as wanted). `bioRad-package` also has `@keywords internal`. All explanatory content of the file will be moved to vignette (see #133). Closing this issue.
