### ISSUE TITLE
reduce package size

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#113]
Total package on CRAN should be less than 5Mb

This devtools check NOTE should be avoided, suggesting no data folder > 1Mb
```
checking installed package size ... NOTE
  installed size is 34.6Mb
  sub-directories of 1Mb or more:
    data      3.1Mb
    extdata  31.2Mb
```

**Comment by adokter** [comment]
We might have to consider a separate data package to come with bioRad, as even a single radar file is much larger than 1 Mb. See https://journal.r-project.org/archive/2017/RJ-2017-026/index.html

**Comment by peterdesmet** [comment]
If you let me know which data should be included in the package, I can easily create one on Zenodo.

**Comment by peterdesmet** [comment]
@adokter agree. Having everything in this repository simplifies things. Hope you can reduce the large files while still keeping them representative and useful for examples.

**Comment by adokter** [comment]
closed by commits 72d34d83feaf6078822f23c3aecd657814bde79d, 6e12aada7be4d20452dddb6ac3c5047a79f290e0 and 0c20d6f27651a0060a9db6ff5870805eca059895

**Comment by adokter** [comment]
documentation changes made the package exceed 5 Mb again
```

**Comment by adokter** [comment]
* checking installed package size ... NOTE
  installed size is  5.1Mb
  sub-directories of 1Mb or more:
    data      1.6Mb
    extdata   2.6Mb
```

**Comment by adokter** [comment]
Let's try to get it approved on CRAN first before putting further effort into reducing the package size, closing for now
