### ISSUE TITLE
create branch for paper review

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#119]
Added a branch `ecography`: https://github.com/adokter/bioRad/tree/ecography

**Comment by adokter** [comment]
*Suggested install instructions to send to ecography editors*:

Please update one statement in step 2 of install instructions at https://github.com/adokter/bioRad

Please use:
```
install_github("adokter/bioRad", ref="ecography")
```
(instead of `install_github("adokter/bioRad")`)

This will install version 3.0.0.of the package in which all the function names are consistent with the paper manuscript.

This package version also has a vignette that covers most of bioRad's functionality, which can be accessed by executing in R: `vignette("bioRad-overview")`

@peterdesmet OK with sending this out?

**Comment by adokter** [comment]
I have added the install instructions in the README.md here:
https://github.com/adokter/bioRad/tree/ecography

**Comment by peterdesmet** [comment]
Yes, slightly updated version:

> To install the bioRad R package, please use:
> 
> ```r
> devtools::install_github("adokter/bioRad@ecography")
> ```
> Instead of `devtools::install_github("adokter/bioRad")` currently mentioned in "Software availability".
> 
> This will install version 3.0.0 of the package in which all the function names are consistent with the paper manuscript.
> 
> This package version also has a vignette that covers most of bioRad's functionality, which can be accessed by executing in R: `vignette("bioRad-overview")`

Is clearer IMO + use of `@ecography` is safer than `ref=`
