### ISSUE TITLE
Adding DBZ to read_pvolfile/read.pvol

### ISSUE THREAD

**Issue by plieper** [adokter/bioRad#123]
It'd be nice to have 'DBZ' added to the list of possible parameters that can be read in by `read_pvolfile`/`read.pvol`. Can be easily by done by:

`function (filename, param = c("DBZ","DBZH", "VRADH", "VRAD", "RHOHV", "ZDR", "PHIDP", "CELL"), sort = TRUE, lat, lon, height, elangle.min = 0, elangle.max = 90, verbose = TRUE, mount = dirname(filename)) `

**Comment by adokter** [comment]
`DBZ` is not an official quantity in the ODIM standard, see http://eumetnet.eu/wp-content/uploads/2017/01/OPERA_hdf_description_2014.pdf, therefore I do not want to include it in the list.

However, when dealing with a not fully ODIM-complient file, users can still read it by adding "DBZ" to the `param` argument.

Marking as 'wontfix' and closing.
