### ISSUE TITLE
Deprecate arguments

### ISSUE THREAD

**Issue by stijnvanhoey** [adokter/bioRad#126]
As referenced in [#112](https://github.com/adokter/bioRad/issues/51#issuecomment-374747768), we can **rename functions** while keeping the old name working as well, as follows for a function oldName(arg1_old,arg2_old that we want to replace with newName(arg1_new,arg2_new) (using roxygen):

```
#' @name oldName-deprecated
#' @rdname bioRad-deprecated
#' @section \code{oldName}:
#' For \code{oldName}, use \code{\link{newName}}.
#' @export
oldName=function(arg1_old, arg2_old){
  .Deprecated("newName")
  newName(arg1_new=arg1_old, arg2_new=arg2_old)
}
```

However, when we **only deprecate the function arguments**, without changing the function name itself, this approach does not work anymore...

I did a quick tour on possible solutions:
- https://ropensci.org/technotes/2017/01/05/package-evolution/ -> collect all arguments, and do checks
- http://r-pkgs.had.co.nz/release.html#compatibility -> argument-specific control loop on presence

I'm tending to use the latter approach. Applied to the `map.R` function `map.ppi`

```
map.ppi <- function(x, map, param, alpha = 0.7, xlim, ylim,
                    zlim = c(-20, 20), ratio, radar.size = 3,
                    radar.color = "red", n.color = 1000, ...) {
...
}
```
this becomes:

```
map.ppi <- function(x, map, quantity, param, alpha = 0.7, xlim, ylim,
                    zlim = c(-20, 20), ratio, radar_size = 3, radar.size = 3,
                    radar_color = "red", radar.color = "red", n_color = 1000, n.color = 1000, ...) {

  if (!missing(param)) {
    warning("argument param is deprecated; please use quantity instead.", call. = FALSE)
    quantity <- param
  }
  if (!missing(radar.size)) {
    warning("argument radar.size is deprecated; please use radar_size instead.", call. = FALSE)
    radar_size <- radar.size
  }
  if (!missing(radar.color)) {
    warning("argument radar.color is deprecated; please use radar_color instead.", call. = FALSE)
    radar_color <- radar.color
  }
  if (!missing(n.color)) {
    warning("argument n.color is deprecated; please use n_color instead.", call. = FALSE)
    n_color <- n.color
  }

...
}
```

In one of the future releases, we can clean this up again and remove the old arguments. I think this will do the job, except of the fact that it does not really cover combine usage of e.g. `n.color` and `n_color`. Although, I do think this would be rather exceptional: old code will just have the old argument and new users will see the message in the documentation about deprecation...

@peterdesmet and @adokter ok to work as such for other argument-only adaptations (e.g. plot functions,...)

**Comment by stijnvanhoey** [comment]
To check the full example for `map.ppi`, see commit https://github.com/adokter/bioRad/commit/308dc7fb24cb2c32beab99a0f52359225877241d

**Comment by adokter** [comment]
yeck, that brings in a lot of lines of code, but I guess there is no alternative. Ok with me!

**Comment by stijnvanhoey** [comment]
> yeck, that brings in a lot of lines of code

I know... If we release every six months, these are gone in 18 months ;-)

**Comment by peterdesmet** [comment]
I would not provide backward compatibility for these: see my comment 
https://github.com/adokter/bioRad/pull/127#discussion_r208295163

 In addition, we can warn users in the changelog of 1.0, or indicate how they can use a specific older version of bioRad if they don’t want to update old code.

**Comment by stijnvanhoey** [comment]
Why we have done the effort to make the new function names backward compatible, but break things on function arguments? I would opt for either (1) break it all the way (remove the function deprecation as well) or (2) step-wise remove the compatibitity all together, i.e. function names and arguments... 

As it is now, we will remove the `bioRad-deprecated.R` in a future release, together with the deprecated function arguments, removing it stepwise [as advised](http://r-pkgs.had.co.nz/release.html). If we wold keep the function renaming deprecation, but ignore the arguments renaming deprecation, we still have the (function deprec) cleanup in a future release. Moreover, we risk to initiate backward compatibility frustation twice for the users instead of once (when they ignore warnings, which is someting people do ;-))...

**Comment by peterdesmet** [comment]
Reading this, I agree with @stijnvanhoey to either support backwards compatibility for functions AND arguments or neither. Since backward compatibility is already implemented, I would leave it as such and remove it in 6 months. That should leave enough time for users to get notified of changes, rather than it being a breaking change from the start.

**Comment by adokter** [comment]
think we can close this one :)

**Comment by peterdesmet** [comment]
Added label `param` for future reference: https://github.com/adokter/bioRad/issues/112#issuecomment-411789178
