### ISSUE TITLE
bioRad 1.x

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#129]
Issue to document things to include in next version of bioRad.

- Remove function deprecation: https://github.com/adokter/bioRad/blob/develop/R/bioRad-deprecated.R
- Remove argument deprecation, see https://github.com/adokter/bioRad/issues/126#issuecomment-411433946
- Param vs quantity (now settled to have both): https://github.com/adokter/bioRad/issues/112#issuecomment-411789178

**Comment by adokter** [comment]
Need to decide whether the first release consistent with the bioRad paper will still be a 0.x version, that we bump to 1.0.

I often see packages staying in the 0.x stage for a long time, maybe a good idea as small instabilities might still show up in the coming months.

**Comment by peterdesmet** [comment]
I'm fine with keeping it at 0.x for a while longer. We should probably bump to 0.3 though, to differentiate with the 0.2.x that we are currently at: https://github.com/adokter/bioRad/releases

**Comment by adokter** [comment]
closing as stale
