### ISSUE TITLE
Create get_param() function

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#132]
I might be missing something, but is there an intuitive way to get a `param` from a `scan`? It seems possible with e.g.:

```r
example_scan$params[[1]]
```

But it might be good to have a:

```r
get_param(scan, param = "DBZH")
```

It will probably be similar in functionality as `get_quantity()`

**Comment by adokter** [comment]
closed by commit 243129220741df659844a49962b76b2e7e66be6c

**Comment by peterdesmet** [comment]
Note: new public functions should be explicitly added to reference overview in _pkgdown.yaml. I will do this. Reopening.

**Comment by peterdesmet** [comment]
Closed in 3ac2e68
