### ISSUE TITLE
is.pvolfile vs is.pvol

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#134]
From https://github.com/adokter/bioRad/issues/110#issuecomment-421929672 by @plieper:

> difference between `is.pvolfile()` and `is.pvol()` I didn't find immediately clear. Apparently you use `is.pvolfile()` when you want to check a file on your computer that you didn't yet read in, and use `is.pvol()` for a file you already did read in (yeah, both are 'files' for me). Adding "Check if a *local* file is a polar volume (`pvol`)" would make it more clear for my, but maybe that's personal :-).

@plieper The same difference exists between `is.vpfile` vs `is.vp`. Did you find those confusing?

Possible solutions:

- Leave as is
- Add `local` to function descriptions "Check if a _local_ file is a polar volume (`pvol`)
- Merge functions into one, so it can check files + objects

**Comment by adokter** [comment]
> Possible solutions:
> -Merge functions into one, so it can check files + objects

For new class objects we are required to include an is.XXX function. So let's at add the `local` to the description

**Comment by peterdesmet** [comment]
Done in 2027c90, branch still needs PR to be included
