### ISSUE TITLE
New description for R base functions

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#135]
From https://github.com/adokter/bioRad/issues/110#issuecomment-421929672 @plieper remarks:

> the descriptions of `summary(<pvol>)`, `is.pvol()` I don't find very informative, because these functions do more than telling you the class of the object. Lower in the list you describe `is.vpfile()`, so I'd do the same here for `is.pvol()` and add a description for `summary(<pvol>)`.

The current description is:

> `summary(<vp>)`, `is.vp()`, `dim(<vp>)`: Object of class `vp`: a vertical profile of birds

I suggest to update to:

> `summary(<vp>)`, `is.vp()`, `dim(<vp>)`: R base functions for an object of class `vp`: a vertical profile of birds

Todo for:

- [x] pvol
- [x] scan
- [x] param
- [x] ppi
- [x] vp
- [x] vpts

@adokter comments?

**Comment by adokter** [comment]
> I suggest to update to: ....

sounds good to me

**Comment by peterdesmet** [comment]
Done in e55d46f, branch still needs PR to be included

**Comment by adokter** [comment]
@plieper @peterdesmet `summary` and `is.XXX` are functions that package developers are required to add for new classes in a package.  I followed the base R practice of documenting `is.XXX` and `summary` functions with the class description, see for example `summary.Date` or `is.ts` in base R.

So the description of this manual page:

> `summary(<vp>)`, `is.vp()`, `dim(<vp>)`: Object of class `vp`: a vertical profile of birds

thus documents the `vp` class primarily. In addition it's associated `summary`, `is` and `dim` reference here as well. 

I suggest to update to:

> `summary(<vp>)`, `is.vp()`, `dim(<vp>)`: class `vp`: a vertical profile of birds
>
> *Description* class vp for a vertical profile of birds, and its associated R base functions

**Comment by peterdesmet** [comment]
@adokter updated again in 7a1a5f75df21f9fdec38184414cea64a40121ed6
