### ISSUE TITLE
Subsetting functions

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#136]
From https://github.com/adokter/bioRad/issues/110#issuecomment-422048975 by @CeciliaNilsson709:

> And I might be missing something, but I don't really get the `'['(ppi)` etc subsetting functions, is that just not the normal subsetting? Seems a bit strange to include to me, and also looks a bit odd like that, but maybe that's normal.

Yes, that is just normal subsetting indeed. But I fully agree that the way the function is referenced (we have no choice there I think) or described:

> Extract by index from a ppi:
> 
> ```
> # S3 method for ppi
> [(x, i)
> ```

is very confusing. Can we:

- Update the function description (suggestions welcome)
- At least provide a simple example
- Reference the function another way??

**Comment by adokter** [comment]
I've added examples and slightly renamed the description.

The way the function is referenced
```
# S3 method for ppi
[(x, i)
```
we cannot control I think.

@peterdesmet please review, leaving closing to you

**Comment by stijnvanhoey** [comment]
I also do not know how the reference to slicing can be adapted, fine for me to close.

**Comment by peterdesmet** [comment]
Updated description slightly in bddbcfc, using the verb "select" (cf. https://www.statmethods.net/management/subset.html). Closing.
