### ISSUE TITLE
Test docker installation instructions on Windows

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#139]
https://github.com/adokter/bioRad/issues/137#issuecomment-423293284 got me thinking what functions require docker. The README currently states:

> You only need to install Docker if:
> 
> - you want to run the vol2bird algorithm.
> - you want to analyze NEXRAD data. The tools to convert NEXRAD data into ODIM format require Docker.

Is it for NEXRAD data only? Do you need it when reading an ODIM pvol file? I think it would be good to rephrase this a bit. And list the functions/function sections that require docker. Is it restricted to the functions from "Reading radar data" and "Creating vertical profiles of biological targets"?

**Comment by adokter** [comment]
> Is it for NEXRAD data only?

No, also when running `calculate_vp` on an ODIM pvol file

> Do you need it when reading an ODIM pvol file?

Not when making plots, but you do when calculating a vertical profile

> list the functions/function sections that require docker.

* `read_pvolfile` for NEXRAD
* `nexrad_to_odim`
* `calculate_vp`

**Comment by peterdesmet** [comment]
Thanks, will clarify this in README when addressing #138

**Comment by peterdesmet** [comment]
The current installation instructions in the README say:

> Docker needs local drives to be available for Docker containers. To enable:
> 
> * right click the Docker (whale) icon on your task or menu bar
> * select settings -> shared drives
> * select the drives where you will be processing radar files
> * click apply

I didn't need to do this for Mac (and the instructions were thus a bit confusing): once installed I could use it right away by opening the app. Can someone test if the following installation instructions are good enough for Windows:

> 1. Go to [Docker Desktop](https://www.docker.com/products/docker-desktop).
> 2. Download Docker for Windows or Mac (free login required) and follow the installation instructions.
> 3. Open the Docker application. The Docker (whale) icon will appear in your menu bar and indicate if it is running correctly.
> 4. In R do `check_docker()`.
> 5. You can now use the bioRad functionality that requires Docker.

**Comment by damianooldoni** [comment]
Installing Docket Desktop only possible for machines running Windows 10. I have Windows 7 Professional on my laptop.  From Docker website:
> Requires Microsoft Windows 10 Professional or Enterprise 64-bit. For previous versions get Docker Toolbox.

You can find Docker Toolbox here: https://docs.docker.com/toolbox/overview/.

However, I get this error and I am not the only one:
https://forums.docker.com/t/docker-quickstart-terminal-error-looking-for-vboxmanage-exe/35028.

**Comment by adokter** [comment]
Hi @damianooldoni @peterdesmet, earlier install instructions mentioned explicitly that only Microsoft Windows 10 Professional or Enterprise 64-bit will work, and Docker toolbox not, but I see that in rewriting documentation that has been removed. I will add it back.

So testing for Windows needs to be done on a Windows 10 Professional or Enterprise machine...

**Comment by peterdesmet** [comment]
Thanks for testing @damianooldoni. @adokter can you close this issue once done?

**Comment by CeciliaNilsson709** [comment]
Reinstalled it just before to check the other issue, and those instructions work 👍. The only extra step I had was I had to "Share" my drive with Docker before I use `calculate_vp`, but that was straight forward.

**Comment by adokter** [comment]
> The only extra step I had was I had to "Share" my drive with Docker

Those setup steps were described in an earlier version of the install instructions:

https://github.com/adokter/bioRad/blame/8a6a854be185925c3acf7871b31b561f7ab082ce/README.md#L66-L74

If these are still correct (@CeciliaNilsson709 ?), I would suggest keeping them

**Comment by CeciliaNilsson709** [comment]
Docker gave a prompt where I could do it directly when I tried to run the command, but those instructions work too. So maybe good to include them just incase someone gets stuck on that for some reason?

**Comment by adokter** [comment]
It also seems the steps are a little different on Mac and Windows, so instructions get a bit lengthy:

Docker needs local drives to be available for Docker containers. To enable:

On Windows:
* right click the Docker (whale) icon on your task or menu bar
* select settings -> shared drives
* select the drives where you will be processing radar files
* click apply

On Mac:
* click the Docker (whale) icon on your menu bar
* select preferences -> file sharing
* add the drives where you will be processing radar files
* click Apply & Restart

**Comment by peterdesmet** [comment]
Thanks!! See https://github.com/adokter/bioRad/pull/179 for an attempt to combine all information while keeping it succinct.

**Comment by adokter** [comment]
Thanks looking good, I'll merge the PR and close the issue 👍
