### ISSUE TITLE
typo's

### ISSUE THREAD

**Issue by plieper** [adokter/bioRad#14]
**README.md:**
_install note 1:_
add 'reboot R' after 
install_github("hadley/ggplot2")
install_github("dkahle/ggmap")

**COMMANDS:**
_cmt:_
twice "of" in first sentence: ... cumulative sum of OF the..  
missing "of" in last sentence: ... as a function OF time ...

_is.scan (and other commands with 'geo' element in de description)_ 
it's should be its:
... geo element of it's parent ...

_[.vplist_ and _[.vpts_
are these commands?

**Comment by adokter** [comment]
Thanks, I got fixed the typo's

Two questions:
* Why does the 'reboot R' command need to be added?
* Also, I thought you wrote earlier that you didn't need these installs on your Mac, or did you after all?

**Comment by plieper** [comment]
- if you don't reboot R after installing both packages from github, it still won't work. maybe obvious for us to do so, though i can imagine not for people less used to programming/installing (read, biologists).
- yes, i did need them after all.

**Comment by adokter** [comment]
Ok thanks, closing this issue
