### ISSUE TITLE
Add news.md + describe changes in 0.3.0

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#144]
I think it would be good to summarize the changes in version 0.3.0. While this can be done in a changelog for the [release on GitHub](https://github.com/adokter/bioRad/releases), we can announce it more directly and nicely to users in a news section on the bioRad website (including a link to deprecated functions).

- News can be included with a `news.md` file: http://pkgdown.r-lib.org/articles/pkgdown.html#news
- Guidelines for writing news: http://style.tidyverse.org/news.html
- Example of news: https://ggplot2.tidyverse.org/news/index.html

@adokter agree to add this? If so, I've already started a changelog at #143, copied here. Still need to rewrite according to style guide, but can you check if anything important is missing?

---

- Use consistent naming convention (#51) and rename relevant bioRad objects (#80), functions (#84) and function arguments (#112) + deprecate old names
- Deprecate `cmt` (#75), `mt` (#76) in favour of `integrate_profile`
- Add plot method for `scan` (#71)
- Split single bioRad.R file into one file per function for easier maintenance (#50)
- Include first tests
- Update pkgdown website + add useful sections to in function reference (#110)
- Update contributors (#90)
- Add bioRad logo (#137)

**Comment by adokter** [comment]
added a first pass for `NEWS.md` in commit 7de6a4eacbd951f33056447b2f2bc0d7b8992f30
