### ISSUE TITLE
decide on versioning

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#149]
Semantic versioning seems a good idea https://semver.org

Given a version number MAJOR.MINOR.PATCH, increment the:

- MAJOR version when you make incompatible API changes,
- MINOR version when you add functionality in a backwards-compatible manner, and
- PATCH version when you make backwards-compatible bug fixes.

I have kept bioRad in a zero version for a long time, so @peterdesmet suggestion to already bump to 0.4 breaks with the versioning I have done so far (would have called it 0.3.1), i.e. I used more a 0.MAJOR.MINOR.PATCH versioning.

To decide whether we use
* MAJOR.MINOR.PATCH versioning
* 0.MAJOR.MINOR.PATCH versioning, until we are really confident about a stable release that we want to call 1.MAJOR.MINOR.PATCH

**Comment by peterdesmet** [comment]
Following this guide: http://r-pkgs.had.co.nz/release.html#release-version, I suggest:

Use MAJOR for breaking changes:

we don’t have those yet (we’re just deprecating), so I would keep that at 0.

MINOR can:

> include bug fixes, new features and changes in backward compatibility. **This is the most common type of release**. It’s perfectly fine to have so many minor releases that you need to use two (or even three!) digits, e.g. 1.17.0.

So for our work, I would work in MINOR chunks, as in: let’s add these bunch of things in the next _minor_ version (0.4.0) or lets postpone that until the one after that (0.5.0). I would release a minor version once we feel like we have something stable again that we want to release to the users.

PATCH:

> I’ll often do a patch release if, after release, I discover a show-stopping bug that needs to be fixed ASAP. Most releases will have a patch number of 0.

So we want to avoid these :smile:

I therefore suggest to use MAJOR.MINOR.PATCH, but we can remain in 0.X.0 quite long. The guide even says that removing functions that were deprecated can be a MINOR release (or MAJOR if we are strict):

> Then, remove the function once you got to 0.7.0 (or if you are being very strict, once you got to 1.0.0 since it’s a backward incompatible change).

**Comment by adokter** [comment]
Ok sounds good, but how to distinguish versioning on Github from CRAN?

I have so far made sure I always added a release tag and changed the version number in DESCRIPTION file whenever I make a new push to master, so that it's clear which version you run as a user if you installed from Github. This has lead to fairly frequent [releases](https://github.com/adokter/bioRad/releases), that are too frequent for releasing on CRAN (that step is not fully automated and a reviewer will look at it, as I understand it).

In addition to your suggestion above, we could use PATCH also for a release that is only on Github, that is too small to release also on CRAN. Let me know what you think on how to deal with this.

**Comment by peterdesmet** [comment]
From the link above (and also http://r-pkgs.had.co.nz/description.html#version), we can use dev versions, in the form of X.X.0.9XXX.

About every merged pull request in master would bump the dev version, see for [this example in the wild](https://github.com/ropensci/rgbif/commits/master/DESCRIPTION). So, with us being at 0.3.0, we are at 0.3.0.9000 for tracking dev. The latest pull request (#147) should have bumped it to 0.3.0.9004 (any number, as long as we increase and stay within 9999) in the DESCRIPTION file (only). Another PR to 0.3.0.9010. That way we can keep the PR loop short (feature branch -> master), i.e. use the [GitHub flow](https://guides.github.com/introduction/flow/) which we prefer over keeping things in develop very long.

Once we think we’re ready for another CRAN release we go for 0.4.0. And then we can continue with 0.4.0.9001 etc. Only MAJOR, MINOR, PATCH would trigger a CRAN release. I would also only create a release on GitHub for those versions (like [here for that same example](https://github.com/ropensci/rgbif/releases)), but there is no harm (just more work) in creating releases for every dev version. I’m just not sure who would use them? When developing, I consider master the latest dev version.

**Comment by peterdesmet** [comment]
To make it easier to decide on the dev version, we could use the merged PR number. So #147 would bump to 0.3.0.9147, so it carries that information. It would mean that we can’t just commit on master and bump (but use PRs, which are the preferred wat to include things in master) and that we can’t let PRs become stale (so that PR 150 is merged before 149). Just a suggestion.

**Comment by adokter** [comment]
Sounds good, using PR number in the dev version name is a good idea, I'll let you make the final call

**Comment by peterdesmet** [comment]
I have assigned all closed issues to a milestone. @adokter would be good if you could triage the open ones in next or later release.

**Comment by peterdesmet** [comment]
@adokter I noticed you [bumped the version](https://github.com/adokter/bioRad/commit/fbe3b0194123362fc362e7f4bab1b1a244662249) to 0.3.1 and [created a release](https://github.com/adokter/bioRad/releases/tag/0.3.1) two days ago. That was before our discussion here. I'll move back to 0.3.0 and remove the release.

**Comment by adokter** [comment]
Sounds good. I kind of got used to keeping my develop branch though. If I merge collaborators' merges to master back into my develop, then there's nothing wrong with that, right?

**Comment by peterdesmet** [comment]
Nope, perfectly ok!

    git merge origin master
