### ISSUE TITLE
select_vpfiles: add data dir to file paths

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#153]
```R
download_vpfiles("2016-10-01", "2016-10-07", "fr", c("tro"))
unzip("frtro201610.zip", exdir = "frtro201610")
vpfiles <- select_vpfiles("frtro201610", "2016-10-01", "2016-10-07")
read_vpfiles(vpfiles)
```

Will generate an empty list, because select_vpfiles does not prepend the file paths with the directory to the file: `01/06/frtro_vp_20161001T0600Z.h5` instead of `frtro201610/01/06/frtro_vp_20161001T0600Z.h5`, so the user needs to prepend this themselves: https://enram.github.io/vp-processing/extract-vp.html#select-date-range-radars

I think it would be more user-friendly if the full path is included...

**Comment by stijnvanhoey** [comment]
When implementing, we have to make sure we properly support the recursive way of file lookup of the function, as a single `file.path` with the main directory won't be sufficient.

**Comment by peterdesmet** [comment]
Updated example:

```R
download_vpfiles("2016-10-01", "2016-10-07", "frtro")
# unzip is done automatically
vpfiles <- select_vpfiles("2016-10-03", "2016-10-04", directory = "frtro")
read_vpfiles(vpfiles)
```
