### ISSUE TITLE
Installation notes

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#154]
Do we still need to include the following 3 installation caveats?

## 32-bits package

On Windows 7, some users have had an installation problem with 32-bits package versions. To suppress the building of 32-bits packages (and use 64-bits only) install with:

```{r eval = FALSE}
devtools::install_github("adokter/bioRad", args="--no-multiarch")
```

## Install note 1: rgdal on linux and mac OS v10.11 or older

bioRad requires an installation of rgdal, which can be fetched from CRAN. The GDAL and PROJ.4 libraries are external to the rgdal package, and, when installing the package from source, must be correctly installed first.

You can use the package managing systems, like Macports on Mac, to install these dependencies, e.g.

```bash
sudo port install proj
sudo port install gdal +expat
```

When compiling rgdal you need to specify the installation directory of the PROJ.4 and GDAL libraries that rgdal depends on. Install from source using the following command (example here with `/opt/local/` as the leading path, which is the directory where the Macports package managing system installs PROJ.4 and GDAL):

```r
install.packages('rgdal',configure.args=c('--with-proj-include=/opt/local/include', '--with-proj-lib=/opt/local/lib', '--with-gdal-config=/opt/local/bin/gdal-config'),type="source")
```

## Install note 2: Virtualbox / Hyper-V conflicts

Unfortunately, Hyper-V can not run together with Virtualbox. When you want to use Virtualbox after running Docker, you need to disable Hyper-V, requiring a reboot of the system. [Here](https://marcofranssen.nl/switch-between-hyper-v-and-virtualbox-on-windows/) some instructions on how to set up a dual-boot system fairly easily (haven't tested this myself yet)

---

If yes, we can (but should probably be rephrased a bit), using the format:

<details>
<summary><strong>Known issues for Windows users</strong></summary>

On Windows 7, some users have had an installation problem with 32-bits package versions. To suppress the building of 32-bits packages (and use 64-bits only) install with:

```{r eval = FALSE}
devtools::install_github("adokter/bioRad", args="--no-multiarch")
```
</details>

**Comment by adokter** [comment]
> 32-bits package

Don't know - some users ran into this, so I think they still might

> Install note 1: rgdal on linux and mac OS v10.11 or older

According to https://cran.r-project.org/web/packages/rgdal/index.html "Windows and Mac Intel OS X binaries (including 'GDAL', 'PROJ.4' and 'Expat') are provided on 'CRAN'", so this may be obsolete for MAc, but linux seems to still need additional installation steps. You first have to install gdal, proj and geos libraries, see https://github.com/datacarpentry/r-raster-vector-geospatial/issues/137:
```
sudo apt-get install libgdal1-dev libproj-dev libgeos-dev
```
> Install note 2: Virtualbox / Hyper-V conflicts
Docker for Windows requires Hyper-V enabled, which still conflicts with other virtualization layers. There is no effort to fix this, see https://github.com/docker/for-win/issues/2153

**Comment by peterdesmet** [comment]
I would leave the README as is (i.e. not include these specific installation notes), close this issue and keep it as reference. If users run into installation issues that are generic, we can opt to include it in README again. @adokter ok?

**Comment by adokter** [comment]
I added a short section to the README for Docker issues that I'm sure still exist
