### ISSUE TITLE
Rename functionality_overview.Rmd

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#165]
@adokter, for what course/workshop did write https://adokter.github.io/bioRad/articles/functionality_overview.html?

I would argue that we don't want to keep that vignette up to date (the #85 and README should cover that) but keep it around as a vignette written for that course and:

- update the name after the course (e.g. `workshop_2018.Rmd`)
- indicate at the top that this vignette was written for a specific course

Note: the vignette is referenced from the README: that link should be updated if the name is updated:

https://github.com/adokter/bioRad/blob/0d3e019ebce1c38a8c910039ad80868b12b3e74f/README.Rmd#L121

**Comment by peterdesmet** [comment]
@adokter can you decide on a better shortname (referring to course e.g. `workshop_2018.Rmd` rather than trying to be generic) for https://adokter.github.io/bioRad/articles/functionality_overview.html, so we can update and close this issue?

**Comment by adokter** [comment]
I updated the vignette with the latest version of the course materials of the Radar Aeroecology Training School in Oklahoma of this year August.

Closed by commit 41cfeade4cf31c18680aefbe3edcb61293ba6ce3

**Comment by peterdesmet** [comment]
Would have been good to keep underscore naming of files, so “rad_aero_2018.Rmd” 😬

**Comment by adokter** [comment]
thanks, fixed
