### ISSUE TITLE
Don't unzip files with download_vpfiles()

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#172]
`download_vpfiles()` currently not only downloads (monthly zips of) vp files, but **unzips these as well**. That makes the function slower than just downloading (see Performance below). I would suggest to remove:

https://github.com/adokter/bioRad/blob/e9355d7bc4f6df0d4b5db2a950fd46854f62d87b/R/download_vpfiles.R#L103-L105

To speed up the download function, and let users unzip the files themselves afterwards (either using R or using their OS). @stijnvanhoey @adokter @cecilianilsson709 any objections?

## Directory structure

The reason this was implemented as such is so that the local directory structure would mimic that of the ENRAM data repository:

```
bejab201808.zip
bejab201809.zip
bewid201808.zip
bewid201809.zip
be/
    jab/
        2018/
            08/
            09/
    wid/
        2018/
            08/
            09/
```

Rather than the default unzipping to:

```
bejab201808.zip
bejab201809.zip
bewid201808.zip
bewid201809.zip
bejab201808/
bejab201809/
bewid201808/
bewid201809/
```

That structure however is not required for `select_vpfiles()`: it searches the data directory recursively based on file names, independent from any directory structure:

```R
length(select_vpfiles(
  directory = "my_data/download",
  date_min = "2018-08-01",
  date_max = "2018-08-31",
  country = c("be")
))
# 17522

# After unzipping zips
length(select_vpfiles(
  directory = "my_data/download_and_manually_unzip",
  date_min = "2018-08-01",
  date_max = "2018-08-31",
  country = c("be")
))
# 17522
```

### With zipping

```R
library(bioRad)
start_time <- Sys.time()
download_vpfiles(
  "2018-08-01",
  "2018-09-30",
  c("be"),
  c("jab", "wid"),
  directory = "my_data/download"
)
end_time <- Sys.time()
difftime(end_time, start_time, units = "secs")
```

Time difference of 355.2779 secs

### Without zipping

```
library(bioRad)
start_time <- Sys.time()
download_vpfiles(
  "2018-08-01",
  "2018-09-30",
  c("be"),
  c("jab", "wid"),
  directory = "my_data/download_and_manually_unzip"
)
end_time <- Sys.time()
difftime(end_time, start_time, units = "secs")
```

Time difference of 202.2632 secs

So a (substantial) time difference of 153 seconds in the case of 17522 files.

**Comment by adokter** [comment]
I think @stijnvanhoey envisioned `download_vpfiles()` to work together with `select_vpfiles()` without having to invoke any external programs like an unzip. So my feeling is that if you strip the unzip from `download_vpfiles()` you have to include it (or make it an option) in  `select_vpfiles()`, @stijnvanhoey?

**Comment by CeciliaNilsson709** [comment]
I think it's nice to get it all done at once 😬. If you have to add another task it will probably not save you much time in the end anyway?

**Comment by peterdesmet** [comment]
Fair enough. 😌 Do we need the retain the directory structure as well, or can that be simplified to 5lettercode/year/month?

**Comment by stijnvanhoey** [comment]
I do understand the idea of @peterdesmet that a function should do 1 thing, but in this case I really do think unzipping is inherently part of the functionality. 

Like @adokter mentions, lots of unforeseen things can probably go wrong when asking people to unzip the downloaded files (either OS-wise or R-wise).

Moreover, I don't think allowing people to unzip the data with their OS outside will help in making the complete analysis reproducible and could break the data analysis pipeline bioRad currently provides. I do not see the benefit of shifting it to a separate function or  make it part of `select_vpfiles()`, as the required time to unzip will be the same anyway.

**Comment by peterdesmet** [comment]
Simplified in #176, but still zips.
