### ISSUE TITLE
Display smaller hex logo for ?bioRad

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#178]
my `pkgdown::rebuild_site()` commit 117eaac38e338695cc49917445ad1015096301a1 has greatly expanded the hexlogo size. This makes it appear way to large, e.g. when doing `?bioRad`.

@peterdesmet I'll pass this one on to you if you don't mind, maybe it is just my build system.

**Comment by peterdesmet** [comment]
High res version of logo was uploaded by me (but not yet in pkgdown website) in https://github.com/adokter/bioRad/commit/b8a5abc103dab33d8a6d0aeb4c3e737c84d1ed4c. It shows correctly in the README and on pkgdown website (with `width="120"`), but will indeed be big when doing `?bioRad`:

<img width="556" alt="screenshot 2018-12-12 at 10 51 26" src="https://user-images.githubusercontent.com/600993/49861736-dad86200-fdfc-11e8-9f30-34fd813245d2.png">


pkgdown [recommends](https://pkgdown.r-lib.org/articles/pkgdown.html#home-page) "240 x 278 pixels", while ours is the size I created it at "520 x 600". I considered the drawback of it appearing big on `?bioRad` less important than everyone having access to the high res version that can be used in posters, presentations, etc.

/cc @sckott same applies for doing `?rgbif`. Any opinion about this?

**Comment by sckott** [comment]
I don't have the sticker in my equivalent of the same file, so not an issue for `rgbif` - i'm happy with the current size

**Comment by adokter** [comment]
Can we switch to the recommended 240x278 pixels, that will make it appear much better (I use `?bioRad` often, and this large size is kind of a shame). We can include a second high res logo version in the repo for people to use as well, with a link to it somewhere.

**Comment by peterdesmet** [comment]
Rather than having two logos, I send a PR to Roxygen to also display the logo at 120px width when doing `?package`: https://github.com/klutometis/roxygen/pull/834

**Comment by peterdesmet** [comment]
I don't consider this a blocker for the 0.4.0 release.

**Comment by peterdesmet** [comment]
PR klutometis/roxygen#834 is now accepted, will be available in next version of roxygen and resolve this issue once we update.
