### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#182]
- [ ] `select_vpfiles()`: check for character vs character vector for radars https://github.com/adokter/bioRad/pull/176#discussion_r240100162
- [ ] `download_vpfiles()`: check for character vs character vector for radars https://github.com/adokter/bioRad/pull/176#discussion_r240100162

**Comment by adokter** [comment]
@peterdesmet this one seems stale

**Comment by peterdesmet** [comment]
Yes, given that test coverage is now checked automatically, I think we can close this one.
