### ISSUE TITLE
Remove releases/tags

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#189]
Remove `0.0.x`, `0.1.x` and `0.2.x` tags from commit history (https://github.com/adokter/bioRad/tags) until we only have 4 tags and associated releases:

tag | release title | changelog
--- | --- | ---
0.1.0 | bioRad 0.1.0 | Check PRs associated with `0.1.x` tags
0.2.0 | bioRad 0.2.0 | Check PRs associated with `0.2.x` tags and everything associated with milestone [0.2.x](https://github.com/adokter/bioRad/milestone/5?closed=1)
0.3.0 | bioRad 0.3.0 | Already written https://github.com/adokter/bioRad/releases/tag/0.3.0
0.4.0 | bioRad 0.4.0 | Already written https://github.com/adokter/bioRad/releases/tag/0.4.0

Best to write changelog first in NEWS.md, then in release. See https://adokter.github.io/bioRad/news/index.html for inspiration and these guidelines: https://style.tidyverse.org/news.html

**Comment by adokter** [comment]
Removed all the old tags, and added 0.2.0 and 0.1.0 release for 0.2.x and 0.1.x issues/milestones. Github now tagged 0.2.0 as 'latest', seems the releases are ordered by that of publication instead of version number, not sure how to change that, @peterdesmet?
