### ISSUE TITLE
time and height alignment of pixels in plot.vpts

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#198]
Pixels are currently
* centralized around the nominal time on the time axis
* centralized around the altitude bin height (HGHT)
However, typical the nominal time is the start time of the acquisition of the polar volume, and HGHT gives the lower altitude of the bin. Each pixels is thus offset by half a pixel in both altitude and time

**Comment by adokter** [comment]
see https://github.com/adokter/bioRad/issues/276 for additional examples by @bart1

**Comment by bart1** [comment]
Thanks for pointing this out I looked for duplicates but could not find them. I'm less sure about the time case, first the acquisition time is not necessarily equal to the interval. Say a complete scan takes 4 minutes but the interval is 15 then the time axis should only be shifted 2 minutes not 7.5. Additionally, typically the first scans are the lower elevation ones (as far as I have seen), these contain most biological information so I'm not sure what is exactly right there.

**Comment by adokter** [comment]
Height offset fixed in #277. Not fixing the time offset for now, as nominal time is ambiguously defined.
