### ISSUE TITLE
change dates into datetime for vpts object

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#20]
`vp` objects have a datetime slot (`vp$datetime`), while `vpts` has a dates slot (`vpts$dates`).

confusing to have different names for these

**Comment by adokter** [comment]
see issue #51

**Comment by adokter** [comment]
We should change dates slot in `vp` to datetime. dates is plural, therefore cannot be generic for both vpts and vp.

**Comment by peterdesmet** [comment]
Will you tackle this issue?

**Comment by adokter** [comment]
@stijnvanhoey For objects of class `vpts` I want to rename `object$dates` into `object$datetime`. I theory this could break older scripts of users if they access this list element directly, which is something I personally do quite often.

Should I keep copies of both, i.e. `object$dates` and `object$datetimes` containing the same vector of dates, or just rename it and be done with it?

**Comment by stijnvanhoey** [comment]
Good point. I do not have much experience with deprecating object structure, but what could work:
- make sure the user can still `get` it (so it does not break things), without having it as an attribute of the object (e.g. by having the possibility using a method), but I do not know if this is possible in R?
- when getting `dates`, provide deprecating message that it will be removed in future release

As such, we could remove it together with the other elements in the future release of next year. If this would not be possible, I would provide them both for now and remove the other one together with all other breaking changes when going to version 2.*

**Comment by adokter** [comment]
Thanks @stijnvanhoey, I think in S3 classes the `get` operator is a simple `$`, and it seems when overloading that operator to generate the warning messages you suggest might cause troubles, or affect performance. So I decided to just rename it.
