### ISSUE TITLE
calculate_vp fails to run vol2bird Docker container after processing a number of files in a list

### ISSUE THREAD

**Issue by ElmoreEcology** [adokter/bioRad#203]
I am processing .gz files from multiple radars over multiple days. When run a loop to generate profiles in hdf5 format from a directory, I get the following errors:

Warning: load_wsr88d_m31_into_radar: Unexpected end of file.
Current sweep index: 0
Last ray read: 702
Error: RSL radar object contains no radial velocity volume...
Error: failed to read radar volume
Error in calculate_vp(file_in, file_out, autoconf = TRUE) : 
  failed to run vol2bird Docker container

The code will successfully process multiple files for one radar on one date, but not all before giving the error code. Can you tell me what these errors mean and how to avoid them?

**Comment by adokter** [comment]
Thanks for your comments. Does the error occur erratically, or only on specific files? If the problem always happens on a specific file, please send me an example (or simply the filename if these are NEXRAD data) - then I can have a quick look what is going on.

**Comment by ElmoreEcology** [comment]
It seems to occur on specific files but I cannot determine why it does so on those files. One in particular that it stops on is KINX20130901_105429_V06.gz. I've been using a set of "test" NEXRAD data on the KINX radar from 09/01/2013. I tried to run through a list from the same radar on 09/02/2013 and have a different set of errors listed below: 

gzip: stdin: invalid compressed data--format violated
read_wsr88d_ray_m31: Read failed.
critical error, cannot open file KINX20130902_021211_V06.gz
Error: failed to read radar volume
Error in calculate_vp(file_in, file_out, autoconf = TRUE) : 
  failed to run vol2bird Docker container

**Comment by adokter** [comment]
I see, I also have problems with these particular files, they seem to be corrupted or at least not readable with the RSL library (https://trmm-fc.gsfc.nasa.gov/trmm_gv/software/rsl/) I use to access the files. You might try to wrap a `try` statement (https://www.rdocumentation.org/packages/base/versions/3.5.2/topics/try) around your calculate_vp call, such that it doesn't interrupt your loop. Good luck.

**Comment by adokter** [comment]
closing for now, seems tied to RSL issue with very specific files only

**Comment by ElmoreEcology** [comment]
Sorry, I should have responded. The try loop works for skipping those specific files that seem corrupted. Thanks for the suggestion

**Comment by adokter** [comment]
that's great!
