### ISSUE TITLE
printf issue in calculate_vp()

### ISSUE THREAD

**Issue by BerendWijers** [adokter/bioRad#211]
On linux R call sh as shell to execute printf as a system call. However, a format option is used ("%q) only available in bash. Therefore, have to force R to make a system call through bash instead of sh

This is the error reproduced in a sh shell
```
~$ sh
$ printf %q "/media/bwijers1/extssd_bwijers/data/pvol/asb/2018/ASB/09/01"
sh: 1: printf: %q: invalid directive
```
Possible fix:
https://stackoverflow.com/questions/40845452/specify-which-shell-to-use-in-r/40845667

**Comment by adokter** [comment]
closed by commit https://github.com/adokter/bioRad/commit/bba8c866765590c8fe8d7e2d06cb6ac4291ca477
