### ISSUE TITLE
Documentation of integrate_profile

### ISSUE THREAD

**Issue by CeciliaNilsson709** [adokter/bioRad#219]
I think there are some typos in the integrate_profile documentation. 

In section:
_Migration traffic rate (mtr) and reflectivity traffic rate (rtr)_

it is stated:
`rtr values are conditional on settings of rcs, while mtr values are not.`

and in section:
_Migration traffic (mt) and reflectivity traffic (rt)_

It is stated:
`rt values are conditional on settings of rcs, while mt values are not.`

Shouldn't these be the opposite? `mtr/mt` values are conditional on `rcs` while `rtr/rt` are not?

I also think it would be good to mention that `rt` and `mt` are cumulative already in the quantities descriptions.

**Comment by adokter** [comment]
Yes you are absolutely right!

**Comment by adokter** [comment]
closed by https://github.com/adokter/bioRad/commit/beab178a3c8e39855c4735684e304df9504d9178
