### ISSUE TITLE
Dev vs stable documentation

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#224]
> @adokter:
> 
> Today I committed this PR (#223), bumping bioRad to version 0.4.0.9223. It adds several functions and updates the documentation. Do we want to regenerate the roxygen site also for these development releases?
> 
> It seems in an ideal world you would want to keep to versions of the site, one for the official CRAN release, and one for the latest development release.
> 
> But if we have to choose for now, what is the best practice? I'm inclined to keep the site up to date with the latest release, even when it's a development release.

I agree to also generate for dev versions, but will look into having documentation for both stable and latest versions. 👍

**Comment by peterdesmet** [comment]
pkgdown supports the creation of development vs stable documentation by setting `development: mode: auto` in `_pkgdown.yml`.

It results in `http://adokter.github.io/bioRad` showing the documentation of the latest **stable** version, i.e. any `x.x.x` release:

![Biological Analysis and Visualization of Weather Radar Data • bioRad (1)](https://user-images.githubusercontent.com/600993/56638992-defc7200-666f-11e9-8b44-9fe07006a904.png)

While documentation for a dev version `x.x.x.9xxx` will be rebuilt at `http://adokter.github.io/bioRad/dev`:

![Biological Analysis and Visualization of Weather Radar Data • bioRad (2)](https://user-images.githubusercontent.com/600993/56639035-fb98aa00-666f-11e9-9ad9-e8a03680774f.png)

So, not necessarily a difference between a minor (`x.x.x`) and a CRAN release, but close enough. As long as we release (minor) versions on CRAN and keep the rest as dev versions, then we have a solution in which `http://adokter.github.io/bioRad` shows the CRAN version and `http://adokter.github.io/bioRad/dev` the latest version.

I like that approach. @adokter what do you think?

**Comment by peterdesmet** [comment]
I created a PR that implements this: #225

**Comment by adokter** [comment]
Nice solution 👍

**Comment by peterdesmet** [comment]
Now live:

http://adriaandokter.com/bioRad/
http://adriaandokter.com/bioRad/dev/

**Comment by adokter** [comment]
Nice! We probably should add crosslinks to these pages, so people now how to find them

**Comment by peterdesmet** [comment]
Indeed, can be done in README.Rmd

**Comment by peterdesmet** [comment]
Having links in both directions (dev to stable and vice versa) probably requires an update to pkgdown (https://github.com/r-lib/pkgdown/issues/943), so we currently have to provide our own solution. I suggest to link from stable to dev (and not the other way around), because the landing page will be for stable.

There are two places where we could add this:

<img width="1028" alt="Screenshot 2019-04-24 at 20 15 19" src="https://user-images.githubusercontent.com/600993/56683640-3d583d80-66ce-11e9-91b3-b0f1943b6279.png">

1. On the left: in the README. Advantage: it also appears in the GitHub repo, so you a direct link. Side note: the links in "Get started" use absolute links to `adokter.github.io/bioRad`, so that the README in the repo links to the website. As a result, those links in `adokter.github.io/bioRad/dev` will also point to `adokter.github.io/bioRad` (and not `dev`).
2. On the right: as a link in the sidebar. Advantage: nicely together with similar "development" links.

We could do both as well. @adokter any preference?

**Comment by adokter** [comment]
I vote for both, but no strong preference

**Comment by peterdesmet** [comment]
Ok added both in 1098a26. And manually included in stable documentation in a42fb86
