### ISSUE TITLE
Add search to pkgdown website

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#227]
Search would make it easier for users (including developers) to find something in the documentation.

Instructions to set this up: https://pkgdown.r-lib.org/articles/pkgdown.html#docsearch-indexing

> Docsearch will contact you via e-mail to confirm you are the website owner.

@adokter I think it's best if you do this as the pkg owner?

**Comment by adokter** [comment]
Ok I applied for docsearch, they will contact within a few days

**Comment by peterdesmet** [comment]
Settings added in 29f58ac. I get a search box locally, but it doesn't work, probably because DocSearch will use the public url. Should be deployed to master to test.

**Comment by adokter** [comment]
> Should be deployed to master to test.

Ok let me know when to do that

**Comment by adokter** [comment]
Ok done

**Comment by adokter** [comment]
> I get a search box locally, but it doesn't work, probably because DocSearch will use the public url. Should be deployed to master to test.

Still not working for me...

**Comment by peterdesmet** [comment]
No, discovered I made a typo. Testing and will commit.

**Comment by peterdesmet** [comment]
Done in 6798cf6, works on local now. Can you merge with master again?

**Comment by adokter** [comment]
Done, and working now, looking very nice!

**Comment by peterdesmet** [comment]
Indeed: 

<img width="996" alt="Screenshot 2019-04-29 at 17 07 08" src="https://user-images.githubusercontent.com/600993/56905844-503d8a00-6aa1-11e9-9a1e-204a08c647ac.png">
