### ISSUE TITLE
units of interval argument in integrate_profile()

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#234]
Units in `integrate_profile` of the `interval_max` argument are in seconds, while `regularize_vpts()` has an interval argument that is in minutes by default, and adjustable by argument `unit`.

These two should be made consistent

**Comment by peterdesmet** [comment]
I would argue for seconds in both.

**Comment by adokter** [comment]
closed by commit https://github.com/adokter/bioRad/commit/ddbce83809a9acc89dbf8b0e50e2459b91394263
