### ISSUE TITLE
auto-detection dependencies on Ubuntu 18.04 and R 3.6.1

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#237]
On a clean install of Ubuntu, the following errors are reported upon installing bioRad:
```
ERROR: dependency ‘httr’ is not available for package ‘ggmap’
* removing ‘/home/adriaan/R/x86_64-pc-linux-gnu-library/3.6/ggmap’
ERROR: dependencies ‘curl’, ‘ggmap’, ‘rgdal’, ‘rhdf5’ are not available for package ‘bioRad’
* removing ‘/home/adriaan/R/x86_64-pc-linux-gnu-library/3.6/bioRad’
```

**Comment by adokter** [comment]
Install of libcurl solved by following these instructions:
```
* installing *source* package ‘curl’ ...
** package ‘curl’ successfully unpacked and MD5 sums checked
** using staged installation
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lcurl
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libcurl was not found. Try installing:
 * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 * rpm: libcurl-devel (Fedora, CentOS, RHEL)
 * csw: libcurl_dev (Solaris)
If libcurl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libcurl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘curl’
* removing ‘/home/adriaan/R/x86_64-pc-linux-gnu-library/3.6/curl’
```

**Comment by adokter** [comment]
Install of httr solved by following the default instructions:
```
> install.packages("httr")
Installing package into ‘/home/adriaan/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
also installing the dependency ‘openssl’

trying URL 'https://cloud.r-project.org/src/contrib/openssl_1.4.1.tar.gz'
Content type 'application/x-gzip' length 1206885 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

trying URL 'https://cloud.r-project.org/src/contrib/httr_1.4.0.tar.gz'
Content type 'application/x-gzip' length 156356 bytes (152 KB)
==================================================
downloaded 152 KB

* installing *source* package ‘openssl’ ...
** package ‘openssl’ successfully unpacked and MD5 sums checked
** using staged installation
Using PKG_CFLAGS=
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because openssl was not found. Try installing:
 * deb: libssl-dev (Debian, Ubuntu, etc)
 * rpm: openssl-devel (Fedora, CentOS, RHEL)
 * csw: libssl_dev (Solaris)
 * brew: openssl@1.1 (Mac OSX)
If openssl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a openssl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
```
This command solved the issue on Ubuntu
```
sudo apt install libssl-dev
```

**Comment by adokter** [comment]
Install of rgdal solved by following the default instructions:

Installation for rgdal fails because it requires gdal to be installed. This command solved the issue on Ubuntu
```
sudo apt install libgdal-dev
```

**Comment by adokter** [comment]
After above installs, also ggmap installs in R correctly on Ubuntu

**Comment by adokter** [comment]
for rhdf5 the same fix as given under #230 works, ie in R:
```
install.packages("BiocManager")
BiocManager::install("rhdf5")
```

**Comment by adokter** [comment]
In summary, on a clean Ubuntu 18.04 install these steps are required before installing bioRad:

In terminal:
```
sudo apt install libcurl4-openssl-dev
sudo apt install libssl-dev
sudo apt install libgdal-dev
```
In R:
```
install.packages("BiocManager")
BiocManager::install("rhdf5")
```

To do:
* need to check why biocViews no longer works in new R versions
* need to check whether CRAN servers have libcurl, libssl and libgdal libraries installed by default
* update install instructions for Ubuntu

**Comment by adokter** [comment]
@peterdesmet would appreciate your ideas on how/whether to document this in the install instructions

**Comment by peterdesmet** [comment]
Not sure, do you think the missing dependencies will catch up at some point?

**Comment by adokter** [comment]
> Not sure, do you think the missing dependencies will catch up at some point?

I think most of these package have in their install descriptions for linux that they need certain things installed with `sudo apt install`, so technically we don't have to mention it I guess - also most of these seem to be present on the CRAN test servers. But maybe it might help users to have a list of non-default packages you need to pre-install on Ubuntu?

I'm mostly concerned about the biocViews trick that makes the package search for bioconductor dependencies, see https://github.com/r-lib/devtools/issues/700 - seems this doesn't work anymore. Also strange this trick isn't documented anywhere properly

**Comment by adokter** [comment]
Installation issue of `rhdf5` is covered under #230, therefore what remains is a decision on how to document the installation procedure on linux

**Comment by peterdesmet** [comment]
Basically include this in instructions: https://github.com/adokter/bioRad/issues/237#issuecomment-513947695

**Comment by adokter** [comment]
closed by commit https://github.com/adokter/bioRad/commit/a4d64e4e74f4e34566d190cc7a57db474dd54b1e
