### ISSUE TITLE
make eta_observed available in range bias correction output

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#251]
Following discussions at UvA on August 27 2019, change output field of `integrate_to_ppi()`:
* rename `correction_factor` to something that avoids the word 'correction'
* add `eta_sum_expected` and `eta_sum_observed` as output field

**Comment by adokter** [comment]
suggestion Bart:
correction = (VID / sum_eta_exp) * sum_eta_obs = (donut shape) * sum_eta_obs
To see effect of the correction, we compare sum_eta_obs and correction

**Comment by bart1** [comment]
The availability was already largely solved I just included the last few changes in #257

**Comment by adokter** [comment]
Thanks @bart1, updated defaults and documentation in commit 4123ccc8d636d1b7cff9469d8d3663e62a02a632, closing
