### ISSUE TITLE
beam profile provides incorrect results

### ISSUE THREAD

**Issue by bart1** [adokter/bioRad#258]
This plot shows the beam profile function has a strange pattern, this is due to the `range` for each elevation angle being used for each call to `gaussian_beam_profile`
``` r
require(bioRad)
#> Loading required package: bioRad
#> Welcome to bioRad version 0.4.0.9243
#> Warning: Docker daemon not found
#> Warning: bioRad functionality requiring Docker has been disabled
#> 
#> To enable Docker functionality, first install Docker
plot(beam_profile(1:3000, 35000, c(1:4,25)),1:3000)
```

![](https://i.imgur.com/iFZnAqX.png)

<sup>Created on 2019-09-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by adokter** [comment]
Indeed a bug. The problem shows up due to the contribution of the highest 25 degree beam. At 35 km the 25 degree beam is way above 3 km, and shouldn't contribute to the profile (except for a normalization constant), but it clearly does in this example

**Comment by adokter** [comment]
closed by commit https://github.com/adokter/bioRad/commit/8ba68580ee7e5c4a0c7a22dc43c24242f71f1d7a
