### ISSUE TITLE
R error: Object dataset1/how does not exist in this HDF5 file.

### ISSUE THREAD

**Issue by plieper** [adokter/bioRad#27]
Reading in a pvol from Baltrad (so real life data) gives the error that dataset1 does not contain 'how', which is true.

`filename <- read.pvol("bewid_pvol_20170110T0900Z.h5")`
`Error in h5readAttributes(filename, paste(scan, "/how", sep = "")) : 
  Object dataset1/how does not exist in this HDF5 file.`

Possible that the read.pvol function needs to be adapted to the current structure of the ODIM h5's?

**Comment by adokter** [comment]
closed by commit https://github.com/adokter/bioRad/commit/24fff2e0c607b1318c24430bab5ed316235af55b
