### ISSUE TITLE
Create bioRad version 0.5.0

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#270]
- [x] Lock down scope: what still to tackle for 0.5.0? See https://github.com/adokter/bioRad/milestone/6
- [x] Write news item: Vaisala IRIS support, `integrate_to_ppi()` and other new functions, pkgdown search, and anything else covered in https://github.com/adokter/bioRad/milestone/6
- [x] DESCRIPTION: Update version to 0.5.0
- [x] README: update https://adokter.github.io/bioRad/dev/articles/range_correction.html to https://adokter.github.io/bioRad/articles/range_correction.html
- [x] Wipe `docs` directory (still contains old files like `rad_aero_18.html`)
- [x] Update pkgdown website
- [x] README: check links, especially https://adokter.github.io/bioRad/articles/rad_aero_19.html and https://adokter.github.io/bioRad/articles/range_correction.html
- [x] Website: verify if search works
- [x] Create release on GitHub, copying info from news
- [x] Verify if pkg was released on Zenodo
- [x] Release pkg on CRAN
- [x] DESCRIPTION: Update version to 0.5.0.9000
- [x] Create new milestone `0.7.0` (`0.6.0` already exists): https://github.com/adokter/bioRad/milestone/10

**Comment by peterdesmet** [comment]
@adokter can you let me know what you still want included in 0.5.0? Once all relevant changes are included in master, I can start the process.

**Comment by adokter** [comment]
@peterdesmet I've trimmed the number of issues to be tackled before 0.5.0 release, any help solving is welcome

**Comment by peterdesmet** [comment]
Ok, will have a look 👍

**Comment by adokter** [comment]
@peterdesmet there is now a version 0.5.0.9297 live on the master branch. I've also built the development website, written a draft release note on github, and copied those to `NEWS.md`. I think it's pretty much ready to go, pending testing (#299).

**Comment by adokter** [comment]
Note that I had to strip `<details>` html blocks from `README.Rmd`, as markdown code in those blocks was not being generated properly. But if you know how to bring them back, great!

**Comment by peterdesmet** [comment]
What is the DOI for `Kranstauber et al. 2020`?

**Comment by adokter** [comment]
not assigned yet, the paper was only accepted last week - we're sending the proofs today or tomorrow.

**Comment by adokter** [comment]
`pkgdown` already has an option to build the `\dontrun{}` code blocks. To build the site with those, you have to make sure you run the latest vol2bird image with mistnet:
```
update_docker(mistnet=T)
```
Then you can build the site with
```
pkgdown::build_site(run_dont_run=T)
```

**Comment by adokter** [comment]
We're on CRAN!
