### ISSUE TITLE
Remove develop branch

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#271]
As discussed with @adokter, the current branch setup is confusing. We now have:

- `master`: contains all accepted changes of the `dev` (!) version of bioRad, i.e. the version that corresponds with http://adriaandokter.com/bioRad/dev/
- `develop`: is generally ahead of master and is used to start pull requests and then bundle those into master.
- `[named-pr-branch]`: whatever name a branch is given when a PR is started (e.g. [grid_input](https://github.com/bart1/bioRad/tree/grid_input))

I would drop the `develop` branch, as there is no relation with the `dev` version of the website. That way, users can start their pull request from the master branch, give that whatever name they want, and it can be merged directly into master (if all checks pass). Before merging, the version number should be bumped (e.g. from `0.4.0.9261` to `0.4.0.9266` for #266). To keep version numbers incremental, it's best to tackle pull requests incrementally too.

Any objections? Note: I will wait for #266 to be accepted before doing so.

**Comment by adokter** [comment]
Hi @peterdesmet, I started this branching model following advice of the NL eScience center, basically following this post:

https://nvie.com/posts/a-successful-git-branching-model/

In this model
* master is always connected to a release:
* develop  always reflects a state with the latest delivered development changes for the next release. Some would call this the “integration branch”.

I've found this quite useful, as sometimes I make small edits that do not really need a full branch of its own, and I don't always want to go through the hassle of creating a release. Therefore working of the develop branch and starting feature branches from there is quite convenient I think.

If we would rename "develop" to "integration", would that resolve the confusion?

**Comment by peterdesmet** [comment]
I get that, but I basically propose the same model as what you want, but where `master` "reflects a state with the latest delivered development changes for the next release." (with a release being a version for CRAN `0.x.0`). That is more or lease the current state of the `master` anyway. I'm ok if you prefer renaming `master` to `develop` to indicate that (but don't know if we loose any "defaults" that way).

Note that:

- Stable `0.x.0` releases are at [releases](https://github.com/adokter/bioRad/releases) and CRAN anyway
- We [write](https://github.com/adokter/bioRad/blob/e0ede427eb34007dc9985302d40cbdab158e0636/README.Rmd#L37) "Alternatively, you can install the latest development version from GitHub with: `install_github(adokter/bioRad)`". To me that is the same as "a state with the latest delivered development changes for the next release" and should thus be `master`
- Minor changes without creating a PR or `0.x.0.9xxx` version update are still ok

**Comment by adokter** [comment]
I get that too, however I thought we agreed that pushing to master ALWAYS results in a new development release, and can only be done through merging a PR and requires updating all documentation and website as well. Typically I also run devtools check in such cases, so there is quite a bit of work and testing involved.

With the current development branch I can be much more relaxed about not breaking something, and still having a branch that gathers all the latest edits and fixes. We would lose that safety buffer if we make master the integration branch.

**Comment by adokter** [comment]
Also note that I don't want people to install from `develop`, only from `master`. So I use `develop` as my latest most up to date branch, but not the one I want people to use and start downloading

**Comment by peterdesmet** [comment]
Ok, fair enough. 😌 In that case I would rename `develop` to `integration`, so there is no confusion with the `dev` version of the package that lives on `master`.

**Comment by stijnvanhoey** [comment]
Is the purpose to let contributors use the [git-flow](https://nvie.com/posts/a-successful-git-branching-model/) (as adviced by NL eScience center)  to develop the package or the [github-flow](https://githubflow.github.io/)?  What I got from the discussion is that you aim for the git-flow, whereas the [guidelines on the documentation](http://adriaandokter.com/bioRad/CONTRIBUTING.html#development-guidelines) website basically point towards the Github flow wit merges towards master (and not develop/integrations). 

I do think we should point contributors to documentation about the used flow and let them focus on [feature branches](https://nvie.com/posts/a-successful-git-branching-model/#feature-branches) as I think using git-flow is increasing the step towards contributing. I recently learnt about https://danielkummer.github.io/git-flow-cheatsheet/ which provides the git flow as adviced by NL eScience center, but bundles this ino a set of commands that are more _declarative_ and could be an option. Unfortunately, this is not straightforward for windows users...

**Comment by adokter** [comment]
Thanks @stijnvanhoey for the background info. Reading those, the main reason I've stuck to git-flow so far is that continuous integration isn't set up yet for bioRad. How about we move the github-flow and delete the develop branch once that's set up, @peterdesmet?

**Comment by peterdesmet** [comment]
:+1: good idea. CI setup requires tests, so we need to tackle that first (maybe we should do a hackathon). Will add a `blocked` label to this issue.

**Comment by stijnvanhoey** [comment]
If it is somewhere beginning next year on a Monday, I'll join the unit-test-hackaton ;-)
