### ISSUE TITLE
HGHT column in vpi has wrong definition

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#272]
At the IRAC meeting I noticed that `integrate_profile()` outputs a `HGHT` column with the definition:

https://github.com/adokter/bioRad/blob/e0ede427eb34007dc9985302d40cbdab158e0636/R/integrate_profile.R#L40

Looking at the code, this definition is incorrect. It is also confusing that a function that integrates height outputs a `HGHT` column. I suggest to update the column header and definition to:

    mean_flight_HGHT: Mean HGHT weighted by density.

`HGHT` in the name indicates that it is based on `HGHT`, `mean` that it is a summary value, and `flight` that it is based on density of birds.

/cc @cecilianilsson709

**Comment by adokter** [comment]
I committed some documentation improvements (https://github.com/adokter/bioRad/commit/c83c692279b2278657258f6db6e37c73677be4cb). @peterdesmet please reopen issue if you disagree.
