### ISSUE TITLE
Should project_as_ppi attach a CRS when project=F?

### ISSUE THREAD

**Issue by bart1** [adokter/bioRad#275]
While investigating some possible changes I noticed `sample_polar` always attached a CRS ( https://github.com/adokter/bioRad/blob/e0ede427eb34007dc9985302d40cbdab158e0636/R/project_as_ppi.R#L169 ). To me it seems this CRS is only valid when project=T? @adokter Is this true? if so I'm happy to make a pull request to fix this.

**Comment by adokter** [comment]
Hi @bart1, yes I see your point. We just have to make sure that change doesn't break anything in the examples etc. Also, it's not entirely true that there isn't any coordinate information, the grid cell sizes and radar location do have an actual definition, we have to make sure that information isn't lost.

**Comment by adokter** [comment]
@bart1 are you aware of CRS definitions that are not 'clamped' to the ground, but that could represent the geometry of the cone swept out by the radar scan at a given elevation? Ideally we would connect something like that in case `project=F`

**Comment by adokter** [comment]
closed by commit https://github.com/adokter/bioRad/commit/e33d47cbe878def56c0b82f37574f3b57390384b

Now removing CRS in case `project=F`. Also disabled `map()` for ppi's that are generated with `project=F`
