### ISSUE TITLE
height for plots

### ISSUE THREAD

**Issue by bart1** [adokter/bioRad#276]
The definition for HGHT in vps is the start of the height interval (see `?summary.vp`). To my minds both `plot.vp` and `plot.vpts` do not follow this definition when plotting. As `plot.vp` puts the point at the start of the interval instead of midle. I would say the middle is more representative. Simairly `plot.vpts` plots from `HGHT-0.5 * interval` to `HGHT+0.5 * interval`. I would propose to raise the height of both plots by `0.5 * interval`. Do you agree?

Ps this assumes vpts stick to the same height definition

**Comment by bart1** [comment]
Sorry these are the examples
``` r
require(bioRad)
#> Loading required package: bioRad
#> Welcome to bioRad version 0.4.0.9261
#> Docker daemon running, Docker functionality enabled
#> No vol2bird Docker image found. Please run update_docker() to download.
data(example_vp)
head(example_vp$data$HGHT)
#> [1]    0  200  400  600  800 1000
plot(example_vp, ylim=0:1)
```

![](https://i.imgur.com/ZtOoJu4.png)

``` r
data("example_vpts")
head(example_vpts$heights)
#> [1]    0  200  400  600  800 1000
plot(example_vpts[1:130], ylim=c(0,1000))
#> Warning in plot.vpts(example_vpts[1:130], ylim = c(0, 1000)): Irregular
#> time-series: missing profiles will not be visible.Use 'regularize_vpts' to
#> make time series regular.
```

![](https://i.imgur.com/yRQlino.png)

<sup>Created on 2019-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by adokter** [comment]
Hi @bart1, thanks, I think this is the same as https://github.com/adokter/bioRad/issues/198, correct? I will reference to your examples there
