### ISSUE TITLE
permission denied while trying to connect to the Docker daemon socket 

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#28]
This is the error I get in my terminal (I'm using Ubuntu 14.04)

checkDocker()
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.26/containers/create?name=hello-world: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

Thanks

-- 
Sergio Cabrera

**Comment by mithun810** [comment]
Check out this link Should be Helpfull
[]https://techoverflow.net/2017/03/01/solving-docker-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket/l)

**Comment by mtarvainen** [comment]
@mithun810 There seems to be extra character at end of your URL which causes browser to redirect into wrong article.

Correct link (which is actually very helpful) is https://techoverflow.net/2017/03/01/solving-docker-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket/

**Comment by adokter** [comment]
Instructions Uli Köhler in link by @mithun810 solves the problem, thanks! Copied the instructions here for easy reference:

The error message tells you that your current user can’t access the docker engine, because you’re lacking permissions to access the unix socket to communicate with the engine.

As a temporary solution, you can use sudo to run the failed command as root.
However it is recommended to fix the issue by adding the current user to the docker group:

Run this command in your favourite shell and then completely log out of your account and log back in (if in doubt, reboot!):
```
sudo usermod -a -G docker $USER
```
After doing that, you should be able to run the command without any issues. Run `docker run hello-world` as a normal user in order to check if it works. Reboot if the issue still persists.

Logging out and logging back in is required because the group change will not have an effect unless your session is closed.
