### ISSUE TITLE
Error reading .ar2v files `Error: wsr88d_decode_ar2v: not found`

### ISSUE THREAD

**Issue by BirgenH** [adokter/bioRad#286]
There appears to be an issue related to reading .ar2v files. 

Same error appears when using nexrad_to_odim(), read_pvolfile(), and calculate_vp(). 

Example code to replicate:
`InputTest = './testData/KEWX20180301_090414_V06.ar2v'`
`library(bioRad)`
`nexrad_to_odim(pvolfile_nexrad = InputTest, pvolfile_odim = gsub("\\.ar2v", "\\.odim", InputTest))`
`read_pvolfile(file = InputTest, verbose = T)`
`calculate_vp(file = InputTest)`

Error message:

> Warning: no user configuration file 'options.conf' found. Using default settings ...
> sh: 1: wsr88d_decode_ar2v: not found
> wsr88d_decode_ar2v not found, aborting ...
> Error in nexrad_to_odim_tempfile(pvolfile_nexrad, verbose, mount) : 
>   Failed to run nexrad_to_odim (rsl2odim) in Docker container.

Checked on two different windows machines. 

`packageVersion("bioRad")`
> ‘0.4.0.9261’

`check_docker()`
> Running docker image with vol2bird version 0.5.0 
[1] 0

**Comment by adokter** [comment]
This is a bug in the latest Docker image (0.5.0) released recently. I will post a hotfix as soon as possible, hopefully by Friday 17th Jan.

**Comment by adokter** [comment]
Hi @BirgenH, please try installing the latest development version (0.5.0.9829), install instructions here: http://adriaandokter.com/bioRad/dev/

and in R update your docker container with `update_docker()`

That should solve this issue
