### ISSUE TITLE
missing wavelength attribute in example_scan

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#298]
example_scan$attributes$how$wavelength is not defined

**Comment by adokter** [comment]
Also applies to `read_pvolfile`, which does not automatically populate wavelength attributes of scan objects, in case wavelength attribute is only defined at the higher polar volume level

**Comment by bart1** [comment]
If you are changing `example_scan` it might also be worth to ensure the order of parameters is the same in as in `example_pvol` , see #365

**Comment by adokter** [comment]
@bart1 the order is fixed as well
