### ISSUE TITLE
testing bioRad 0.5.0

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#299]
@peterdesmet @bart1 @CeciliaNilsson709, I'm close to finishing up the 0.5 release of bioRad.

You can install it with
```
devtools::install_github(adokter/bioRad@develop)
```

I'd appreciate some help in testing the two most important new features:
- `integrate_to_ppi`: this function calculates a spatially explicit image of vertically integrated density, while correcting for the changing beam overlap with distance from the radar. @bart1 and I just got a methods paper accepted on this topic in Remote Sensing.
- `apply_mistnet`: this is an implementation of the MistNet segmentation model developed by Tsung-Yu Lin, Subhransu Maji, Daniel Sheldon and others at UMass.

Could you verify these two functions work as they should? (e.g. by running the code examples in the documentation). Improvements to the documentation where necessary would also be much appreciated.

Thanks!

**Comment by adokter** [comment]
FYI we have a hard deadline for this [0.5.0 release](https://github.com/adokter/bioRad/milestone/6) on CRAN by Feb 17 (this release also includes some mandatory fixes by CRAN that they require by this time)

**Comment by adokter** [comment]
@peterdesmet there is now a version 0.5.0.9297 live on the master branch. I've also built the development website, written a draft release note, and updated `NEWS.md`. I think it's pretty much ready to go, pending testing ...

**Comment by CeciliaNilsson709** [comment]
Both `integrate_to_ppi` and `apply_mistnet` worked for me, the latter with these warnings:

```
> example_pvol <- apply_mistnet("~/volume.h5")
Loaded user configuration file 'options.conf' ...
Warning: radial velocities will be dealiased...
Warning: using MistNet, disabling other segmentation methods
Warning: MistNet segmentation model has been trained on S-band data, results at other radar wavelengths may be unreliable!
Warning: requesting 5 elevations scans, but only 3 available
Warning: Requested elevation scan at 3.500000 degrees but selected scan at 2.500000 degrees
Warning: Requested elevation scan at 4.500000 degrees but selected scan at 2.500000 degrees
Warning: no spectrum width data found for MistNet input scan 0, initializing with values 0 instead.
Warning: no spectrum width data found for MistNet input scan 1, initializing with values 0 instead.
Warning: no spectrum width data found for MistNet input scan 2, initializing with values 0 instead.
Warning: no spectrum width data found for MistNet input scan 3, initializing with values 0 instead.
Warning: no spectrum width data found for MistNet input scan 4, initializing with values 0 instead.
Running MistNet...done
Warning: scan used multiple times as MistNet input, ignoring segmentation 4/5
Warning: scan used multiple times as MistNet input, ignoring segmentation 5/5
```

**Comment by adokter** [comment]
@peterdesmet we need to add a warning to documentation of `download_basemap` function that users need to update `ggmap` - I found that map selection with `maptype` argument otherwise doesn't work

**Comment by peterdesmet** [comment]
Regarding `download_basemap`, I'm trying to understand the expected behaviour before documenting. Logged as a separate issue: https://github.com/adokter/bioRad/issues/303

**Comment by peterdesmet** [comment]
`ggmap` is 3.0.0 at CRAN and GitHub. If we require that version, it needs to be added as such in description.
