### ISSUE TITLE
Enable collapsable <details> in README again

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#300]
Collapsable `<details>` were used in the README to hide specific verbose installation instructions. Since the Markdown in these sections no longer rendered on pkgdown 1.4.1, these were removed in https://github.com/adokter/bioRad/commit/da3337daaea25b44a552a31a73a0fae9268fabcb.

I have reported this as https://github.com/r-lib/pkgdown/issues/1220. Hopefully pkgdown can reintroduce Markdown parsing in details, after which we can bring them back in the README.

**Comment by peterdesmet** [comment]
This will be fixed in the next version of pkgdown: https://github.com/r-lib/pkgdown/commit/8ac4be486815c3b7856fdba4c5ebbf3a8d330bb1

**Comment by peterdesmet** [comment]
@adokter this is now fixed, but make sure you upgrade your pkgdown to 1.5.1 before building the website. Close issue once verified the detail sections work on the website.

**Comment by adokter** [comment]
details sections work, had to add one manual line break before one details section (d5f19bf).
