### ISSUE TITLE
Download basemap example does not work

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#303]
Tried to test examples at http://adriaandokter.com/bioRad/reference/download_basemap.html#examples

Installed latest version of ggmap:

```R
devtools::install_github("dkahle/ggmap")
```

1. Tried default from example, which seems to work fine

```R
ppi <- project_as_ppi(example_scan)
basemap <- download_basemap(ppi)
map(ppi, map = basemap, param = "DBZH")
```

2. Tried "osm", but I get exactly the same basemap, which seems a bug

```R
basemap_osm <- download_basemap(ppi, source="osm")
map(ppi, map = basemap_osm, param = "DBZH")
```

3. Tried "google", and got error as expected:

```R
basemap_google <- download_basemap(ppi, source="google")
>  Error: Google now requires an API key.
       See ?register_google for details. 
map(ppi, map = basemap_google, param = "DBZH")
```

4. Tried `maptype` from example but got an error:

```R
basemap_sat <- download_basemap(ppi, maptype = "satellite")
> Error: invalid stamen maptype, see ?get_stamenmap 
map(ppi, map = basemap_sat, param = "VRADH")
```

**Comment by adokter** [comment]
With "osm" I get this message:
```
Error: 'get_openstreetmap' is defunct.
Use 'OSM is at least temporarily not supported, see https://github.com/dkahle/ggmap/issues/117.' instead.
```
So I will remove "osm" as an option.

Regarding 4., satellite is not a valid option for stamen, but e.g. toner-light is.
