### ISSUE TITLE
Unclosed tag on hidden deprecated functions page

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#326]
http://adriaandokter.com/bioRad/reference/bioRad-deprecated.html:

<img width="536" alt="Screenshot 2020-02-21 at 14 00 03" src="https://user-images.githubusercontent.com/600993/75036575-7ad65480-54b2-11ea-93af-9844736dc9c0.png">

**Comment by adokter** [comment]
@peterdesmet can this one be closed now that deprecated functions have been removed?

**Comment by peterdesmet** [comment]
Likely, let's wait until we have the new website. That page will still exist.
