### ISSUE TITLE
Don't allow negative values for radar cross section

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#336]
It is currently possible to set a negative `rcs`:

```R
rcs(vp) <- -11
```

I wonder if the user should get a warning or error for this? If fixed, uncomment test:

https://github.com/adokter/bioRad/blob/b8cd9d97399772d178a02915a35afafc056c5def/tests/testthat/test-rcs.R#L8

**Comment by adokter** [comment]
this one was already fixed in previous release
