### ISSUE TITLE
How to access v speed data from a vplist object

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#34]
I can access `v` data for a single vp file:

    bioRad::fetch(vp_files[1], quantity = "v")

But if I want to access it for 4 vp files (= vplist object):

    bioRad::fetch(vp_files, quantity = "v")

I get the `dens` values back instead of `v` (which is not even the first attribute), even though according to the bioRad documentation, the `fetch` function should work on 3 class types:

> ### Arguments
> 
> x: a vp,vplist or vpts object
> quantity: a profile quantity, one of "HGHT","u","v","w","ff", "dd","sd_vvp","gap","dbz","eta", "dens","DBZH","n","n_all","n_dbz","n_dbz_all".

I know I can get at the data with `vp_files[1]$data`, but fetch is the recommended function... is the fact that `dens` is returned a bug or am I doing something wrong?

**Comment by adokter** [comment]
closed by commit 5b44f95bd016ac92f7e82ca90837730e054c4498

**Comment by peterdesmet** [comment]
Confirmed fixed! 👌
