### ISSUE TITLE
get_quantity error when extracting heights from vpts

### ISSUE THREAD

**Issue by barthoekstra** [adokter/bioRad#352]
Not really a showstopper, but `height` is not stored in the `vpts` quantities list, so `get_quantity()` requesting height bins throws an error:

```r
> data("example_vpts")
> get_quantity(example_vpts, "height")
Error in `rownames<-`(`*tmp*`, value = x$height) : 
  attempt to set 'rownames' on an object with no dimensions
```

**Comment by adokter** [comment]
Thanks @barthoekstra, that's one we have to fix. You can access the heights for now with `example_vpts$height`

**Comment by CeciliaNilsson709** [comment]
`get_quantity()` returns quantities per height bin, so for `vpts` it returns a matrix with the quantity requested over time and height bin. So "height" itself can't be requested, but yes, you can access it through `example_vpts$height`. I'll see if we can get a better error message...

I wonder if this confusion is due to "height" meaning "height bin" in a vp's but in a vpi "mean flight altitude"? That is pretty confusing.

**Comment by barthoekstra** [comment]
I merely stumbled across this bug while testing the output of `get_quantity()` on the first quantity listed in the docs, so I was not confused about different meanings of height in this case. The docs suggest `get_quantity()` should work consistently for `vp`s and `vpts`s, so that's why I reported it. Otherwise accessing it through e.g. `example_vpts$height` would make sense indeed, though then heights (with an s) would be more intuitive (as we're not looking at the values per bin anymore).

**Comment by adokter** [comment]
> I wonder if this confusion is due to "height" meaning "height bin" in a vp's but in a vpi "mean flight altitude"? That is pretty confusing.

Yes we should change the column `height` in `vpi` object to something more intuitive, like `flight_altitude`, @CeciliaNilsson709 maybe you can make an issue for that with a suggestion

**Comment by adokter** [comment]
Once that is changed, `get_quantity()` can be adjusted to work for `height` as well, i.e. return the height of the altitude layers.

**Comment by adokter** [comment]
> I wonder if this confusion is due to "height" meaning "height bin" in a vp's but in a vpi "mean flight altitude"? That is pretty confusing.

@CeciliaNilsson709 it is, I now remember that I wanted to rename it to something like `flight_altitude`, but then I realized that mathematically the operation on something like speed (`ff`) in going from vpts -> vpi, is identical to what happens for height, i.e. in the vpi it is a weighted average over height of the quantity in the vpts. So therefore I thought if we do not rename `ff` and other quantities, we whould also keep `height` in the vpi with the same name.

But maybe we can add something in the documentation to avoid this confusion? Maybe you can add an issue for that if you think it would be helpful

**Comment by CeciliaNilsson709** [comment]
Ah, yes @barthoekstra, you are right, that is wrong in the documentation, I can change that now while updating it anyway!

But just to be clear: `get_quantity()` _always_ outputs the height together with the requested quantity, so adding height also as a quantity would just lead to a vector with two height columns. But we can of course do that, just for completion? What do you think @adokter? I can do that now too if you want.

I'll open a separate issue for height/height bin/flight altitude!

**Comment by CeciliaNilsson709** [comment]
<img width="1036" alt="Screenshot 2020-04-16 at 20 03 07" src="https://user-images.githubusercontent.com/28302378/79490773-b22e3100-801d-11ea-8096-a0f2e3fdf6f0.png">

Is this better? What does 📝 🦸 think? @peterdesmet

**Comment by adokter** [comment]
add height as an option for consistency in https://github.com/adokter/bioRad/commit/d8d9c8a8483e614e473983058c959d76cd724d34

**Comment by peterdesmet** [comment]
@adokter I know this was done to fix a test with `integrate_to_ppi()`, but I'd argue that adding height is not consistent: it is not a quantity, it is the bin by which everything else is organized. Can this be solved another way?

**Comment by adokter** [comment]
It can be solved in a different way, but not really my preference. Height is one of the profile columns that you need very often in analyses, and the latest changes made the info very hard to to find (only by digging into the class structure by vp$data$height). I think users will find it confusing that they have to use different commands to get to such basic information. In addition, in ODIM profiles (as well a our own ODIM bird profile, https://github.com/adokter/vol2bird/wiki/ODIM-bird-profile-format-specification) height is referred to as a quantity just like the other columns.

**Comment by CeciliaNilsson709** [comment]
So, it just repeats what the height is at all the heights then? Doesn't make much sense but I guess for consistency 🤷‍♀️

**Comment by peterdesmet** [comment]
In that case, we should probably add `height` as a quantity in documentation then (on `vp` and `get_quantity()`?

**Comment by adokter** [comment]
> So, it just repeats what the height is at all the heights then? Doesn't make much sense but I guess for consistency 

Yes, can come in handy though if you want to do matrix algebra on the quantity matrices

> In that case, we should probably add height as a quantity in documentation then (on vp and get_quantity()?

Yes, I've added that already yesterday

**Comment by adokter** [comment]
Added height to `vp.R` documentation too (a1cb13275b0ffa64598a134acbd609030a224f3f)
