### ISSUE TITLE
dimension of bioRad classes reported by dim()

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#355]
Subsetting the example data currently works as follows:

```
# vp
example_vp$data[height,quantity]

# vpts option 1
example_vpts$data[[quantity]][height, time]
# vpts option 2
example_vpts[time]$data[height, quantity]

# vpi
example_vpi <- integrate_profile(example_vpts)
example_vpi[time,quantity]

# param
example_param[range,azim]

# scan
example_scan$params[[param]][range,azim]

# pvol
example_pvol$scans[[scan]]$params[[param]][range,azim]
```
For the example data we have the following index maxima:
```
height = 25
time = 1934
quantity = 15 of 16
scan = 3
param = 5
range = 480
azim = 360
```
Checking `dim()`:
```
dim(example_vp)    #> c(25,16)      correct
dim(example_vpts)  #> c(25,1934,15) incorrect, given above subsetting you expect c(15,25,1934) or c(1934,25,15)
dim(example_vpi)   #> c(1934, 12)   correct
dim(example_param) #> c(480,360)    correct
dim(example_scan)  #> c(5, 480,360) correct
dim(example_pvol)  #> NULL          incorrect, should be 3
```
Suggesting the following changes:
* `dim(example_vpts)` should give `c(1934,25,15)` i.e. `c(time, height, quantity)`, which follows the vpts subsetting order of option 2, and is the most similar in order to `dim(example_vp)`
* `dim(example_pvol)` should give `c(3)` i.e. the number of scans only. We can't give the deeper dimensions, as they may be different for various scans.

**Comment by peterdesmet** [comment]
Fixed in commits referenced above
