### ISSUE TITLE
Bug in readvp.table function

### ISSUE THREAD

**Issue by plieper** [adokter/bioRad#37]
When using the readvp.table function on a vol2bird text output, I got the following error:

`Warning message:
In Ops.factor(heights[-1], heights[-length(heights)]) :
  '-' not meaningful for factors`

This `heights` seems to be a factor, the problem can be solved by putting `heights = as.numeric(as.character(heights))` under `  heights = data[[1]]$HGHT`in the function.

**Comment by adokter** [comment]
Please add (part of the) file on which you get this error. Could it be that your input text file is corrupted?

**Comment by plieper** [comment]
[fiika_deal_false_redkite.txt](https://github.com/adokter/bioRad/files/1098080/fiika_deal_false_redkite.txt)

`> vptable <- readvp.table("fiika_deal_false_redkite.txt", radar="ika")`
`Warning messages:
1: In readvp.table("fiika_deal_false_redkite.txt", radar = "ika") :
  No 'wavelength' argument provided, assuming radar operates at C-band
2: In Ops.factor(heights[-1], heights[-length(heights)]) :
  '-' not meaningful for factors`

Can be solved by changing:
`heights = as.numeric(as.character(heights))`

After I adjusted `heights` I wanted to plot de time series, but I got following error:
`Error in log(plotdata) : non-numeric argument to mathematical function`
Turns out values in `vptable$data` are `character` instead of `numeric`. I didn't yet check it, but I think this causes the error.

**Comment by adokter** [comment]
@plieper your file does not have the correct output, it should be the exact text generated by the stdout of vol2bird, e.g. as you get in:
```
vol2bird volume.h5 > stdout.txt
```
Or with multiple calls of vol2bird you can append to the textfile as in:
```
vol2bird volume.h5 >> stdout.txt
```
Once you are done processing, you can read the textfile with bioRad:
```
readvp.table(stdout.txt)
```
