### ISSUE TITLE
regularize_vpts() fails on vpts with profiles with duplicate timestamps

### ISSUE THREAD

**Issue by CeciliaNilsson709** [adokter/bioRad#371]
Some profiles in the repository have duplicate timestamps, see #235. @adokter fixed this is in `plot.vpts()` by dropping profiles from the time series. However duplicate timestamps also cause `regularize_vpts()` to fail, so I added the same code snippet from `plot.vpts()` to `regularize_vpts()`, which seems to work. I accidentally merged it directly to develop, so it's there now 😬, sorry.

Additionally, now I am wondering if this is the right thing to do. Does anyone know why there are duplicates? The profiles don't seem identical. Are we losing information by just using the first one in a timestamp? Users are being warned that profiles are dropped, but wanted to hear what people think about it.

**Comment by peterdesmet** [comment]
Reference to your commit: https://github.com/adokter/bioRad/commit/4eac9cedeee915b9577bfb183ff63bf02d733414

**Comment by adokter** [comment]
@peterdesmet this one is already part of bioRad release 0.5.2 (#388) which I just submitted to CRAN, but I haven't documented or checked it yet I now realize.

**Comment by peterdesmet** [comment]
Even though this is now part of 0.5.2, I have not documented this in NEWS.md as I didn't have time to review this. So I'm leaving this issue in milestone 0.6.0.

**Comment by adokter** [comment]
@peterdesmet just a ping that this one is only a quick documentation fix, not sure if we want to document in 0.6.0 as this was part of 0.5.2
