### ISSUE TITLE
urgent: CRAN fix for c.POSIXct()

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#375]
```
Dear maintainer,

Pls see
<https://CRAN.R-project.org/web/checks/check_results_bioRad.html>: more
ERRORs for r-devel will follow.

I recently fixed a bug report for c.POSIXct so that this now reasonably
coerces all arguments to POSIXct.  

In your case, a traceback for the failing example shows

11: c.POSIXct(x, y)
10: c(x, y)
9: plot_wind_barbs(barbdata$date, barbdata$height, 180 + barbdata$dd, 
      barbdata$ff, cex = 0.7)
8: plot.vpts(example_vpts)

so the problem is with the c(x, y) in  plot_wind_barbs where x is a
datetime object and y is not.

Can you pls fix as necessary?

Please correct before 2020-05-12 to safely retain your package on CRAN.

Best
-k
```

**Comment by adokter** [comment]
@peterdesmet we should fix this one together with the PRs for unit tests that we will publish soon. Deadline is soon, May 12 the package will be archived on CRAN.

**Comment by adokter** [comment]
Error seems to thrown here:
https://github.com/adokter/bioRad/blob/5ee47fe2058d15e640aa28d80fb83491cde6165e/R/plot.vpts.R#L411-L412

**Comment by adokter** [comment]
Some more info from Kurt Hornik on the change:
```
The svn log entry is

r78312 | hornik | 2020-04-27 13:56:36 +0200 (Mon, 27 Apr 2020) | 4 lines

Allow combining POSIXct with POSIXlt objects, and other things coercible
to POSIXct (PR#16241).

but what changed is as I wrote:  c.POSIXct now coerces all arguments to
POSIXct.
```

**Comment by adokter** [comment]
@peterdesmet @niconoe I don't fully understand what has changed, but fix https://github.com/adokter/bioRad/commit/33ef0c2838a0fe427fae60c6977137b63b4c4508 should bypass the call to `c.POSIXct()` that throws the error.

Can't really test this as it's only available on the latest R dev version, and I can't easily compile that on OSX

**Comment by peterdesmet** [comment]
Regarding:

> we should fix this one together with the PRs for unit tests

Ok, I'm churning through the PRs. #361 almost done. Are your #348 and #362 ready for review, or are you working further on those? I think we should wait with including 365.

Will this be a 0.5.1 hotfix or a 0.6?

**Comment by niconoe** [comment]
Can I do something to help solving this? I have access to Windows/linux machines if that helps... What should be done? Install/compile R development version and try to install bioRad `develop` branch?

**Comment by peterdesmet** [comment]
@adokter @bart1 Integrating #361 has raised a 4 errors:

```R
test-integrate_to_ppi.R:9: error: integrate_to_ppi() raster argument produces expected output
Can't find quantity `height` in `x`.
```

Can you adapt the test?

**Comment by adokter** [comment]
@niconoe 
> Can I do something to help solving this? I have access to Windows/linux machines if that helps... What should be done? Install/compile R development version and try to install bioRad develop branch?

Yes, such testing on the latest dev version for Windows/linux would be great.

There are also https://win-builder.r-project.org/ and https://builder.r-hub.io/ which performs tests, but it takes often > half hour to get test results, and hard to debug ..

**Comment by adokter** [comment]
@peterdesmet 
> Are your #348 and #362 ready for review, or are you working further on those? I think we should wait with including 365.

Those are ready for review, and can be merged after that. Agree with waiting with #365 

> Will this be a 0.5.1 hotfix or a 0.6?
I think it should be 0.6 - Some new functionality, lots of new unit tests and documentation improvements, so more than just a hotfix. Note I started already https://github.com/adokter/bioRad/blob/develop/NEWS.md update

**Comment by adokter** [comment]
> @adokter @bart1 Integrating #361 has raised a 4 errors:
fixed in https://github.com/adokter/bioRad/commit/ba3189e56ab956ee664ac13e93eef2c11876b60f, tests were ok, minor fix in get_quantity.vp() to allow selection of height quantity.

**Comment by adokter** [comment]
I'll run `rhub::check_for_cran` overnight to check the package on R-hub

**Comment by adokter** [comment]
R-hub test fails on get_quantity unit test. Commenting out the test and will submit R-hub test again.

Build ID: | bioRad_0.5.1.9344.tar.gz-e5cdbbd80ca843529840fcc0aa94e850
-- | --
Platform: | Fedora Linux, R-devel, clang, gfortran
Submitted: | 44 minutes 9.2 seconds ago
Build time: | 44 minutes 8.4 seconds


```
* checking tests ...
  Running ‘testthat.R’ [26s/26s]
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  ══ testthat results  ═══════════════════════════════════════════════════════════
  [ OK: 282 | SKIPPED: 38 | WARNINGS: 4 | FAILED: 17 ]
  1. Failure: get_quantity.vpts() return a matrix for all 16 quantities (@test-get_quantity.R#104) 
  2. Failure: get_quantity.vpts() return a matrix for all 16 quantities (@test-get_quantity.R#105) 
  3. Failure: get_quantity.vpts() return a matrix for all 16 quantities (@test-get_quantity.R#106) 
  4. Failure: get_quantity.vpts() return a matrix for all 16 quantities (@test-get_quantity.R#107) 
  5. Failure: get_quantity.vpts() return a matrix for all 16 quantities (@test-get_quantity.R#108) 
  6. Failure: get_quantity.vpts() return a matrix for all 16 quantities (@test-get_quantity.R#109) 
  7. Failure: get_quantity.vpts() return a matrix for all 16 quantities (@test-get_quantity.R#110) 
  8. Failure: get_quantity.vpts() return a matrix for all 16 quantities (@test-get_quantity.R#111) 
  9. Failure: get_quantity.vpts() return a matrix for all 16 quantities (@test-get_quantity.R#112) 
  1. ...
  
  Error: testthat unit tests failed
  Execution halted
```

**Comment by niconoe** [comment]
I'm trying to install bioRad on Windows (R dev version), but get the following error:

````
githubinstall("bioRad", ref="develop")
Suggestion:
 - adokter/bioRad  R package for extracting and visualising biological signals from weather radar data
Do you want to install the package (Y/n)?  Y
Downloading GitHub repo adokter/bioRad@develop
Installing 42 packages: fields, ggmap, ggplot2, lubridate, lutz, raster, rgdal, rhdf5, sp, tidyr, viridisLite, viridis, maptools, dotCall64, gtable, isoband, scales, tibble, Rcpp, farver, labeling, munsell, RColorBrewer, vctrs, colorspace, utf8, png, tidyselect, plogr, purrr, stringi, dplyr, generics, spam, maps, RgoogleMaps, plyr, rjson, jpeg, bitops, Rhdf5lib, gridExtra
Installing packages into ‘C:/Users/nicol/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
Erreur : Failed to install 'bioRad' from GitHub:
  (converti depuis l'avis) unable to access index for repository https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.1:
  impossible d'ouvrir l'URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.1/PACKAGES'
De plus : Warning message:
In fread(download_url, sep = "\t", header = FALSE, stringsAsFactors = FALSE,  :
  Found and resolved improper quoting out-of-sample. First healed line 4848: <<Puriney	honfleuR	"Evening, honfleuR" by Seurat>>. If the fields are not quoted (e.g. field separator does not appear within any field), try quote="" to avoid this warning.
> 
```

**Comment by adokter** [comment]
Hi @niconoe, I would try enabling bioconductor repo's as well, in addition to CRAN, with:
```
setRepositories(ind = 1:2)
```
It needs bioconductor to install the rhdf5 package. You can also try to install it manually, see https://www.bioconductor.org/packages/release/bioc/html/rhdf5.html

**Comment by niconoe** [comment]
I'm still struggling:

- enabling bioconductor doesn"t change the error.
- while manually installing `rhdf5` it has issues linking with `rhdf5lib` (that I also installed, first via bioconductor then directly from GitHub). After a successful compilation step: 

````
Error in library.dynam(lib, package, package.lib) : 
  La DLL 'Rhdf5lib' est introuvable : elle n'est peut-être pas installée pour cette architecture ?
Calls: :: ... asNamespace -> getNamespace -> loadNamespace -> library.dynam
Exécution arrêtée
Error in library.dynam(lib, package, package.lib) : 
  La DLL 'Rhdf5lib' est introuvable : elle n'est peut-être pas installée pour cette architecture ?
Calls: :: ... asNamespace -> getNamespace -> loadNamespace -> library.dynam
Exécution arrêtée
Error in library.dynam(lib, package, package.lib) : 
  La DLL 'Rhdf5lib' est introuvable : elle n'est peut-être pas installée pour cette architecture ?
Calls: :: ... asNamespace -> getNamespace -> loadNamespace -> library.dynam
Exécution arrêtée
...
````

**Comment by adokter** [comment]
Not sure why your build fails either @niconoe, many packages are having issues since recent R 4.0 release, maybe that is part of it

**Comment by adokter** [comment]
R-hub build (`rhub::check_with_rdevel()`, running Debian Linux, R-devel, GCC) passes when commenting out unit tests #377 and #378
