### ISSUE TITLE
reduce package size to below 5MB

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#376]
Addition of unit tests has brought the package size (again) above 5MB:

Tarball now 5012207 bytes, need to shed at least 12207 bytes for a CRAN submission

```
$ du -hc
476K	./man/figures
828K	./man
588K	./vignettes
204K	./tests/testthat
208K	./tests
400K	./R
4.0K	./build
1.7M	./inst/extdata
1.3M	./inst/doc
2.9M	./inst
1.4M	./data
6.3M	.
6.3M	total
```

**Comment by adokter** [comment]
@peterdesmet we either have to tackle #376 within the next week or so, but I think it will be quite a bit of work to do that properly

My suggestion is to reduce the size of https://github.com/adokter/bioRad/blob/master/vignettes/ecog12354-fig-0002-m.jpg which you added as part of the bioRad vignette

**Comment by peterdesmet** [comment]
I can add the external files to Zenodo quite easily, but I guess updating all the examples will be some work?

Can’t we hotlink the images to the url of the paper for now?

**Comment by adokter** [comment]
> I guess updating all the examples will be some work?

Yes, and so many tests/examples depend on them that it slows down checks quite a bit, so prefer waiting

> Can’t we hotlink the images to the url of the paper for now?

Maybe, worth a try - what we need is the figure not showing up (or being reduced in size) in the tarball that is generated when you run `R CMD build bioRad`. Not sure if the file stays out of the tarball during vignette generation, even when you hotlink.

**Comment by peterdesmet** [comment]
Hotlinked in e0b3f3b, but the figure does get encoded in the bioRad.html in the tarball 😕. Total size of tarball 4.5MB.

**Comment by adokter** [comment]
```
du -hc man vignettes tests R inst data
528K    man/figures
908K    man
 68K    vignettes
260K    tests/testthat
264K    tests
464K    R
2.6M    inst/extdata
2.6M    inst
1.4M    data
5.7M    total
```

**Comment by adokter** [comment]
@bart1 it's mostly the radar example data we need for running the examples

**Comment by bart1** [comment]
I just checked gz compressing vpts.txt does not help

**Comment by peterdesmet** [comment]
There is the suggestion to store the raw example data on Zenodo: https://github.com/adokter/bioRad/issues/317. Doing so might need updates to the examples (`{dontrun}`) and tests (`skip_if_offline()`).

**Comment by adokter** [comment]
I just recreated the tarball, it seems we can ignore the devtools::check warning on package size, because the tarball is still below 5Mb, which is what is the hard requirement:
```
4094723 bioRad_0.7.0.9597.tar.gz
```
