### ISSUE TITLE
Composite multiple PPI params at once

### ISSUE THREAD

**Issue by barthoekstra** [adokter/bioRad#390]
Currently the `composite_ppi()` function only composites PPIs for a single parameter. 

I need to make composites of a bunch of parameters stored in some PPIs, which obviously I'd like to do all at once rather than separately and then rebuilding a single composite PPI. So I've tweaked the composite function to accept a vector of `param` names (similar to how param selection in `read_pvolfile()` works) and a vector of `method` names to set methods per parameter type (if necessary).

As this is a ‘prototype’ function, I was wondering if you're interested in including this functionality (if you're not already working on it anyways). If so, even though I'm not 100% sure I'll end up using it myself, I could contribute and improve [my existing code](https://github.com/barthoekstra/bioRad/blob/composite_ppi/R/composite_ppi.R) to make composite PPIs of multiple parameters.

**Comment by adokter** [comment]
Hey @barthoekstra, yes this would be very useful and was on the todo-list, so please make a PR, thanks!

**Comment by barthoekstra** [comment]
Ok. Work in progress.

**Comment by adokter** [comment]
closed by #393
