### ISSUE TITLE
allow parallelization of docker commands

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#397]
Currently each session initializes a docker container with the same name (`vol2bird`). To allow parallelization with e.g. `future_lapply()` each R-sessions needs to assign a unique docker container name, otherwise the docker containers of different sessions will conflict.

**Comment by bart1** [comment]
This is kind of addressed for local docker installs now in #497 it might not be worth investing time in fixing the docker setup as the work on a `vol2bird` R package is going on

**Comment by adokter** [comment]
closed by #517
