### ISSUE TITLE
get_scan and multiple similar elevation scans have same angle

### ISSUE THREAD

**Issue by bart1** [adokter/bioRad#414]
Currently `get_scan` returns "Returns the scan (scan) from a polar volume (pvol) with elevation angle closest to elev.". Some radars have multiple scans at the same elevation. It is kind of ambiguous what is currently returned in those cases. I think the might be a few options, I guess the current implementation returns the first one with the minimal difference. In this case it might be worth to issue a warning about other scans being available with the same height. Alternatively multiple scans might be returned as a list that match the criteria. This might be a breaking  change for some people. @adokter what do you think?

**Comment by adokter** [comment]
Hi @bart1, I agree to avoid breaking changes the default should remain returning only a single scan is returned. I like the idea of giving a warning when multiple scans have the same elevation angle. How about adding a third (optional) boolean argument `all` (default: `FALSE`) that when `TRUE` returns a list of scans if multiple scans are present at the same elevation?
