### ISSUE TITLE
What are the legend.ticks and legend_ticks parameters in plot.vpts()

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#421]
`plot.vpts()` has `legend.ticks` and `legend_ticks` as parameters. I assume only one works (which one?) and what is the default?

https://github.com/adokter/bioRad/blob/33ec6ed50f64029b7cc097b819aa1c9afa0587d4/R/plot.vpts.R#L67

**Comment by adokter** [comment]
This is a result of the renaming refactoring we did, legend.ticks is the deprecated form of legend_ticks. Use legend.ticks will throw a warning that you should update to legend_ticks.

Probably about time to get rid of these deprecated function arguments throughout the package, there are quite a few of them

**Comment by adokter** [comment]
default values depend on the quantity you are plotting:
https://github.com/adokter/bioRad/blob/33ec6ed50f64029b7cc097b819aa1c9afa0587d4/R/plot.vpts.R#L126-L159

**Comment by adokter** [comment]
In the case of dbz and DBZH quantities default values also depend on the radar wavelength (C-band (<10 cm) or S-band (>=10 cm), i.e. taking care that the color scales are sort of comparable at the two wavelengths

**Comment by adokter** [comment]
I felt it was getting a little complicated to document the default legend_ticks, but if you want to have a go at it @peterdesmet please go ahead

**Comment by adokter** [comment]
closed by commit 588b306
