### ISSUE TITLE
export pvol to ODIM hdf5

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#423]
Prototype function to write `pvol` object to an ODIM hdf5 file:
```
write.pvol=function(pvol,file,nodata=-9999,undetect=-9998){
  h5createFile(file)
  fid=H5Fopen(file)
  for (i in 1:length(pvol$scans)){
    h5createGroup(file,paste("dataset",i,sep=""))
    for (j in 1:length(pvol$scans[[i]]$params)){
      h5createGroup(file,paste("dataset",i,"/data",j,sep=""))
      data=pvol$scans[[i]]$params[[j]]
      data=replace(data,is.nan(data),undetect) # replace NaN before NA!
      data=replace(data,is.na(data),nodata)
      h5write(data,file,paste("dataset",i,"/data",j,"/data",sep=""))
      group=paste("dataset",i,"/data",j,"/what",sep="")
      h5createGroup(file,group)
      gid=H5Gopen(fid,group)
      h5writeAttribute(attributes(data)$param,gid,"quantity")
      h5writeAttribute(1,gid,"gain")
      h5writeAttribute(nodata,gid,"nodata")
      h5writeAttribute(0,gid,"offset")
      h5writeAttribute(undetect,gid,"undetect")
      H5Gclose(gid)
    }

    # write scan attributes
    attrgroupnames=names(pvol$scans[[i]]$attributes)
    for(k in 1:length(attrgroupnames)){
      group=paste("dataset",i,"/",attrgroupnames[k],sep="")
      h5createGroup(file,group)
      gid=H5Gopen(fid,group)
      attrgroup=pvol$scans[[i]]$attributes[[k]]
      attribnames=names(attrgroup)
      for (l in 1:length(attribnames)){
        h5writeAttribute(attrgroup[[l]],gid,attribnames[l])
      }
      H5Gclose(gid)
    }
  }

  # write volume attributes
  attrgroupnames=names(pvol$attributes)
  for(k in 1:length(attrgroupnames)){
    group=paste(attrgroupnames[k],sep="")
    h5createGroup(file,group)
    gid=H5Gopen(fid,group)
    attrgroup=pvol$attributes[[k]]
    attribnames=names(attrgroup)
    for (l in 1:length(attribnames)){
      h5writeAttribute(attrgroup[[l]],gid,attribnames[l])
    }
    H5Gclose(gid)
  }

  H5Fclose(fid)
}
```

**Comment by adokter** [comment]
@barthoekstra do you think we could include a function in the next release (we are flexible, but aiming for within the next 1-2 weeks or so), or will this require more time?

**Comment by barthoekstra** [comment]
Hi @adokter

Sorry, maybe I wasn't clear enough about this in our last meeting, but I really need someone else's input for a solution to the problem I'm facing. The version of `write_pvolfile()` (see branch w/ same name) works fine, except for writing the attributes. As you can see in the code (it's a bit of a mess, sorry), I've tried several ways of writing attributes to the HDF5 file. Somehow, regardless of the method of writing attributes, the `rhdf5` functions seem to always write scalar attribute values to a 1D array, whereas these are written with `H5S_SCALAR` dimensions in the original file. This causes a difference in the resultant `pvol` if the written .h5 file is read in again. I cannot really tell how problematic this is for other use cases (e.g. vol2bird), but the resultant file at least is not a valid ODIM type anymore according to `get_odim_object_type()`... For an illustration, see [this version](https://github.com/adokter/bioRad/files/6725480/volume.zip) of volume.h5 (zipped to upload here) after it's been written by `write_pvolfile()`.

The data writes fine, btw. `h5diff` only detects differences between the ways attributes are stored.

If you don't mind about this difference, I can polish the code so it can be included in the next release.

**Comment by adokter** [comment]
Hi @barthoekstra,

Got it thanks - I just tried out running vol2bird on the volume.h5 written by your function, and I get identical results, so there seems to be no problems there. Also, for `get_odim_object_type()` I get the correct returned value (PVOL):
```
> get_odim_object_type("~/tmp/write_pvolfile/volume.h5")
[1] "PVOL"
> get_odim_object_type("~/tmp/write_pvolfile/volume_bioRad_orig.h5")
[1] "PVOL"
```
Can you confirm this result?

I think you can go ahead and polish the code for inclusion in the next release.

**Comment by barthoekstra** [comment]
Hmm, strange. I retried it and indeed `get_odim_object_type()` returns `"PVOL"`, but somehow the tests in `test-pvolfile.R` do not succeed. Anyways, glad to hear vol2bird works fine with this `pvol`. I'll polish it up.

**Comment by adokter** [comment]
I added a small tweak to `get_odim_object_type()` that makes sure a character is returned, and not a character-array of length 1: https://github.com/adokter/bioRad/blob/e120126803d81584dd2adb87516d664a55f92d52/R/pvolfile.R#L68-L71

the tests in `teast-pvolfile.R` should now pass

**Comment by barthoekstra** [comment]
See #470

**Comment by bart1** [comment]
As this pull request is merged the issue can be closed
