### ISSUE TITLE
Set up GitHub actions to automatically test, document, build + use master branch

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#428]
To make maintenance easier, I want to set up GitHub actions to automatically test code contributions, document/style code and build the pkgdown website. Todo:

- [x] R CMD Check: on every PR commit
- [x] Remove `develop` branch
- [x] document: on `/document` in PR: works, see https://github.com/adokter/bioRad/pull/348/commits/7cc1b1c30d258651bbeefdef2cbf15d7cf468536
- [x] styler: on `/styler` in PR
- [x] pkgdown build to `gh-pages`: on accepted PR and master commits
- [x] Use `gh-pages` rather than docs for website (in repo settings)
- [x] Remove `/docs` directory
- [x] Test coverage
- [x] Badges

## Optional

- [ ] `write_codemeta()`
- [ ] Build README.Rmd: `devtools::build_readme()`
- [ ] ~Bump version based on PR~

**Comment by damianooldoni** [comment]
About the problems with pr-commands actions as mentioned in https://github.com/adokter/bioRad/pull/427, I think I discovered the reason, which is quite simple: they are correctly written. It's just that they cannot have an effect on the PR which is creating them! I could use them in packages I am maintainer only after I merged them to `master`. 
In this specific case, the PR merged to `develop`. I think any other PR pointing to `develop` could using them by the adding the typical trigger words in PR body.

**Comment by peterdesmet** [comment]
@damianooldoni Oh, so you need have those workflows be part of the repository already, before you can use them?

**Comment by peterdesmet** [comment]
@adokter I think we are at a point where we no longer need the `develop` branch. I think it was created to avoid exposing users to development releases, but we have better tools for that now:

## Stable releases

- Download from CRAN: `install.packages("bioRad")` or even `devtools::install_github("adokter/bioRad@0.5.2")`
- Website at http://adokter.github.io/bioRad (only gets updated for non-dev releases)

## Development releases on `master`

- Download with `devtools::install_github("adokter/bioRad")`
- Website at http://adokter.github.io/bioRad/dev/ (updated with every commit to `master`)
- Code functionality guaranteed by:
  - Running tests for every commit or PR to `master`
  - Optional: protecting `master` branch by requiring at least on review on PR
- PRs default to to `master` (already the case)

I think keeping the `develop` branch will be more confusing than helpful.

**Comment by adokter** [comment]
@peterdesmet ok to get rid of develop branch if you think that's better.

We started it following this post:
https://nvie.com/posts/a-successful-git-branching-model/

and I've liked it as a way of not having to come up with new branch names all the time, but I see the name develop can be confusing.

**Comment by peterdesmet** [comment]
@adokter can you change the repository settings and use the `gh-pages` branch as source for the website rather than `/docs`? The branch has all necessary files now.

**Comment by adokter** [comment]
changed repo settings to use the root of `gh-pages` branch
