### ISSUE TITLE
ggmap dependency

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#429]
The ggmap dependency fails automated builds on Windows ([example](https://github.com/adokter/bioRad/pull/427/checks?check_run_id=2526515092)). This is a [known problem](https://community.rstudio.com/t/orphaned-package-on-windows-build/84165), because ggmap is orphaned. People seem to solve the issue by moving `ggmap` from `Imports` to `Suggests` in `DESCRIPTION`. I tried that, but that failed all builds, as it is seen as a requirement.

@bart1 @adokter any ideas on how to fix this. Can we drop the option to plot on google maps?

**Comment by peterdesmet** [comment]
@adokter can you run `rhub::check_on_windows()` and see what warnings you get? I can't, because it requires email verification by the main author.

**Comment by adokter** [comment]
Build completes fine:
https://builder.r-hub.io/status/bioRad_0.5.2.9419.tar.gz-c67c940660564e508e497f9dd38ba0a8
https://artifacts.r-hub.io/bioRad_0.5.2.9419.tar.gz-c67c940660564e508e497f9dd38ba0a8/

**Comment by peterdesmet** [comment]
Issue is likely to be solved at https://github.com/dkahle/ggmap/issues/311#issuecomment-836550941. I have:

- Required ggmap to be >=3.0.0: https://github.com/adokter/bioRad/commit/a87fb29916537ff578bf4c96539342a114ebaf1a
- Disabled Windows builds for now: https://github.com/adokter/bioRad/commit/b98a56c618a2a5d21e5f80680f53cf4bffe37f26

@adokter with forcing 3.0.0 or up in DESCRIPTION we can likely remove this too:

https://github.com/adokter/bioRad/blob/33ec6ed50f64029b7cc097b819aa1c9afa0587d4/R/download_basemap.R#L63

**Comment by adokter** [comment]
removed the ggmap version check in https://github.com/adokter/bioRad/pull/466
