### ISSUE TITLE
read.pvol: velocity stored as VRAD instead of VRADH

### ISSUE THREAD

**Issue by plieper** [adokter/bioRad#43]
The function `read.pvol` allows parameters `param = c("DBZH", "VRADH", "RHOHV", "ZDR", "PHIDP",
  "CELL")`, however in the OPERA polar volumes, velocity is stored under the name `VRAD`. As a consequence, VRAD-scans are not read by `read.pvol`. Simply adding `"VRAD"` to the parameter list solves the problem. See also issue #39 for another problem with the same function.

**Comment by adokter** [comment]
closed by commti 538259b26a4dfab0df68f77e0ca063440b1c51ac
