### ISSUE TITLE
scan_to_spatial point location

### ISSUE THREAD

**Issue by bart1** [adokter/bioRad#430]
I was doing some work on details in radar images. I was curious what point `scan_to_spatial` refers to. It looks like its the upper left corner (see example below). My implicit assumption was it referred to cell/range gate centers. First I would document this and maybe add an option for cell centers or make that the default?

``` r
require(bioRad)
#> Loading required package: bioRad
#> Welcome to bioRad version 0.5.2.9419
#> Docker daemon running, Docker functionality enabled (vol2bird version 0.5.0)
ppi<-project_as_ppi(example_scan, 10, 1200, xlim=12.8517+c(.45,.5), ylim=c(.4,.45)+56.3675)
#> Warning in proj4string(obj): CRS object has comment, which is lost in output
plot(ppi)
```

![](https://i.imgur.com/L4iilJ7.png)

``` r
pts<-scan_to_spatial(example_scan)
ptsdf<-as.data.frame(pts)
require(ggplot2)
#> Loading required package: ggplot2
plot(ppi)+geom_point(data=ptsdf[!is.nan(ptsdf$DBZH),], aes(x=x,y=y, color=DBZH))
```

![](https://i.imgur.com/8EOpHee.png)

<sup>Created on 2021-05-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bart1** [comment]
ps this is under the assumption `project_to_ppi` is correct. if we know what is desirable I can implement it

**Comment by adokter** [comment]
Hi @bart1,

Thanks for spotting this one. The exact position of pixels is a tricky issue, and not all radar data are fully consistent in how the location of pixels is defined, so there might be some ambiguity. Would be good to double-check the ODIM standard on this issue.

In these lines we could add a half-bin in the azimuth and range dimensions, that might be a simple fix
https://github.com/adokter/bioRad/blob/33ec6ed50f64029b7cc097b819aa1c9afa0587d4/R/scan_convert.R#L42-L43

**Comment by bart1** [comment]
Ok I looked in this a bit further, also reading the odim specs (https://www.eumetnet.eu/wp-content/uploads/2019/01/ODIM_H5_v23.pdf). The fix you propose and I had in my head is the most obvious one and would work place the point in the center of the range gate for most cases. 

There are however two related issues. Some radars seem to use the `rstart` attribute. I did a quick scan over the baltrad radars (one per country, first scan)
```
        a1gate   elangle nbins nrays   rscale rstart
BE/JAB/    137 0.5000000   300   360  500.000  0.000
CH/ALB/      0 0.3790341   420   360  499.998  0.000
CZ/BRD/    190 0.1000000   650   360  400.000  0.000
DE/ASB/    100 0.8020020   180   360 1000.000  0.000
DK/BOR/    313 0.4779050   472   360  500.000  0.500
EE/HAR/    330 0.5000000   830   360  300.000  0.900
ES/ALM/    394 0.4998779   240   450 1000.000  0.125
FI/ANJ/    188 0.3000000   500   360  500.000  0.000
FR/ABB/    227 0.4000000   267   360  960.000  0.000
HR/BIL/    184 0.5000000   241   360 1000.000  1.000
NL/DHL/     83 0.3000000   838   360  223.500  0.000
PL/BRZ/      0 0.5000000   250   360 1000.000  0.000
PT/FAR/    194 0.1000000   200   720  500.000  0.000
SE/ANG/    354 0.5000000   480   360  500.000  0.000
SI/LIS/    293 0.5000000   249   360 1000.000  0.000
SK/JAV/    192 0.0000000   960   360  250.000  0.000
```
It looks like some countries use this attributes but biorad does not account for it. I visually checked PPI for `DKBOR` and `EEHAR` with some wind turbine locations and applying the proposed shift would probably make the data more plausible.

Similar there is an attribute `astart` the french radar `FRABB` seems to use this (-.5 degrees). Which if i read the docs correctly mean the whole image needs to be rotated half a degree. Looking at some plots for this it might be indeed the better fit.

The fixes for these later two problems are however probably more elaborate as they would have implications throughout the package. (each time going from Cartesian to polar and vise versa).

A few radars also report start and end azimuths for each ray. The deviations from the implied values are however not very big (about 0.02 degrees). I think trying to this correctly is probably a bit over the top.

**Comment by adokter** [comment]
Hi @bart1, I think we can go ahead then with adding the 0.5 pixel size offset to `scan_to_spatial()`, and create a new issue (to be tackled later) to implement the use of `astart` and `rstart` throughout the package
