### ISSUE TITLE
Use `remotes` to automatically install rhdf5

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#464]
I think we can use `remotes` in DESCRIPTION to install rhdf5 from bioconductor, rather than requiring users to do:

    setRepositories(ind = 1:2)

**Comment by adokter** [comment]
closed by 36de1962df53d4cf838dc27e06b8f7ea2ab88c84, d113ee8b461a7d425c7acc255ef4cb610a1d88a8 and 894225a40b2997a700446a14c575a1f6c2879a05
