### ISSUE TITLE
Structure tutorials

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#48]
1. pvol exploration: structure of pvol
2. ppi: ppi plot
3. vol2bird: pvol → vp, docker
4. vp exploration: structure of vp
5. vpts exploration: vp → vpts, timeseries plots
6. vpts filtering: df + yaml
7. vpts aggregation

**Comment by adokter** [comment]
@peterdesmet I presume this one is obsolete, closing for now
