### ISSUE TITLE
Split R code over files by function

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#50]
For better readability, maintenance and collaboration, I'd suggest to split [bioRad.R](https://github.com/adokter/bioRad/blob/master/R/bioRad.R) (and the other R files) in logical files: one per function (and its helper functions), with the same name as that function.

@adokter these are all the functions I found, per current file. It's quite the list 😅 At first glance, think it would be better to group these by what they do (e.g. bind, vintegrate) that their data type (vp, vplist).

## bioRad.R

function | remarks | new file | reference section
--- | --- | --- | ---
checkDocker | in NAMESPACE | docker.R | docker interface
updateDocker | in NAMESPACE | docker.R | docker interface
startContainer | | docker.R | 
readOdimProfileData | | hdf5.R
quantityName | | hdf5.R
readvp | in NAMESPACE | vp.R | vertical profile
is.vpfile | in NAMESPACE | vp.R | vertical profile
is.pvolfile | in NAMESPACE | pvol.R | polar volume
h5ODIMobject | in NAMESPACE | hdf5.R | loading data
is.ODIMfile | | hdf5.R
readvp.list | in NAMESPACE | vp.R | loading data
c.vp | in NAMESPACE | vp.R | vertical profile
bind | in NAMESPACE | profile.R | vertical profile time series
bind.vp | | bind.R
bind.vplist | | bind.R
bind.vpts | | bind.R
summary.vplist | | vplist.R
print.vplist | | vplist.R
vpts | in NAMESPACE | vpts.R | vertical profile time series
vptsHelper | | vpts.R
vintegrate | in NAMESPACE | vintegrate.R | migration traffic and vertical integration
vintegrate.vp | | vintegrate.R
vintegrate.vplist | | vintegrate.R
vintegrate.vpts | | vintegrate.R
print.vpts | | vpts.R
vol2bird | in NAMESPACE | vol2bird.R | processing vertical profiles from polar volume data
rsl2odim | in NAMESPACE | vol2bird.R | processing vertical profiles from polar volume data
rsl2odim_tempfile | | vol2bird.R
readvp.table | in NAMESPACE | vp.R | loading data
regularize | in NAMESPACE | vpts.R | vertical profile time series
mtr | in NAMESPACE | traffic.R | migration traffic and vertical integration
summary.vp | | vp.R
is.vp | in NAMESPACE | vp.R | vertical profile
is.vplist | in NAMESPACE | vplist.R | vertical profile
summary.vpts | | vpts.R
is.vpts | in NAMESPACE | vpts.R | vertical profile time series
dim.vpts | | vpts.R
[.vpts | | vpts.R
vpts2vp | | vpts.R
rcs | in NAMESPACE | rcs.R | vertical profile attributes
rcs.vp | | rcs.R
rcs.vplist | | rcs.R
rcs.vpts | | rcs.R
rcs.vivp | | rcs.R
rcs<- | in NAMESPACE | rcs.R | vertical profile attributes
rcs<-.vp | | rcs.R
rcs<-.vplist | | rcs.R
rcs<-.vpts | | rcs.R
rcs<-.vivp | | rcs.R
sd_vvp | in NAMESPACE | sd_vvp.R | thresholding attributes
sd_vvp.vp | | sd_vvp.R
sd_vvp.vplist | | sd_vvp.R
sd_vvp.vpts | | sd_vvp.R
sd_vvp<- | in NAMESPACE | sd_vvp.R |  thresholding attributes
sd_vvp<-.vp | | sd_vvp.R
sd_vvp<-.vplist | | sd_vvp.R
sd_vvp<-.vpts | | sd_vvp.R
mt | in NAMESPACE | traffic.R | migration traffic and vertical integration
cmt | in NAMESPACE | traffic.R | migration traffic and vertical integration
suntime | in NAMESPACE | suntime.R | sunrise and sunset functions
night | in NAMESPACE | suntime.R | sunrise and sunset functions
day | in NAMESPACE | suntime.R | sunrise and sunset functions
day.vp | | suntime.R
day.vplist | | suntime.R
day.vpts | | suntime.R
day.pvol | | suntime.R
beamheight | in NAMESPACE | beam.R | radar and scan geometry
earthradius | | beam.R
beamwidth | in NAMESPACE | beam.R | radar and scan geometry
dbz2eta | in NAMESPACE | dbz_eta.R | converting reflectivity and reflectivity factor
eta2dbz | in NAMESPACE | dbz_eta.R | converting reflectivity and reflectivity factor
fetch | in NAMESPACE | dispatch.R | extracting data from bioRad objects
fetch.vp | | fetch.R
fetch.vplist | | fetch.R
fetch.vpts | | fetch.R
as.data.frame.vpts | in NAMESPACE | vpts.R | extracting data from bioRad objects

## bioRad.plot.R

function | remarks | new file  | reference section
--- | --- | --- | ---
is.na2 | | plot_profile.R
plot.vp | in NAMESPACE | plot_profile.R | vertical profile
plot.vivp | in NAMESPACE | plot_profile.R | migration traffic and vertical integration
plot.vpts | in NAMESPACE | plot_profile.R | vertical profile time series
plot_wind_barbs | | plot_profile.R

## bioRad.ppi.R

function | remarks | new file  | reference section
--- | --- | --- | ---
read.pvol | in NAMESPACE | pvol.R | polar volume
read.scan | | scan.R
read.quantity | | scan.R
print.pvol | | pvol.R
print.scan | | scan.R
print.param | | param.R
summary.pvol | | pvol.R
is.pvol | in NAMESPACE | pvol.R | polar volume
summary.scan | | scan.R
is.scan | in NAMESPACE | scan.R | polar scan
dim.scan | in NAMESPACE | scan.R | polar scan
summary.param | | param.R
is.param | in NAMESPACE | param.R | polar scan parameter
elangle | in NAMESPACE | elangle.R | radar and scan geometry
elangle.scan | | elangle.R
elangle.pvol | | elangle.R
getscan | in NAMESPACE | pvol.R | polar scan
ppi | in NAMESPACE | ppi.R | projecting scans as a plan position indicator
[.ppi | | ppi.R
ppi.param | | ppi.R 
ppi.scan | | ppi.R
composite | in NAMESPACE | composite.R | compositing
samplePolar | | ppi.R
wgs2proj | | ppi.R
proj2wgs | | ppi.R
cartesian2polar | | ppi.R
safeSubset | | ppi.R
polar2index | | ppi.R
get_colorscale | | colorscale.R
get_colorscale_fill | | colorscale.R
get_zlim | | param.R
plot.ppi | in NAMESPACE | ppi.R
basemap | in NAMESPACE | map.R  | overlaying radar scans on a map
map | in NAMESPACE | map.R | overlaying radar scans on a map
add.alpha | | map.R
map.ppi | | map.R
print.ppi | | ppi.R
summary.ppi | | ppi.R
is.ppi | in NAMESPACE | ppi.R | projecting scans as a plan position indicator
dim.ppi | in NAMESPACE | ppi.R | projecting scans as a plan position indicator

## download_vp.R

function | remarks | new file  | reference section
--- | --- | --- | ---
url_existence | in NAMESPACE | vp_repo.R | loading data
download_vp | in NAMESPACE | vp_repo.R | loading data
match_filenames | in NAMESPACE | vp_repo.R | loading data
retrieve_vp_paths | in NAMESPACE | vp_repo.R | loading data

**Comment by adokter** [comment]
@peterdesmet yes the number of functions has been growing steadily, it's time to break them up according to functionality.

**Comment by peterdesmet** [comment]
Do you do a first attempt by populating new_file in the tables above? So we can get the low hanging fruit out of the way?

**Comment by adokter** [comment]
@peterdesmet my suggestions above. Some ambiguity whether you want to group methods functions by class or by functionality, but this seemed to make most sense to me fore now

**Comment by stijnvanhoey** [comment]
I would also translate the classification (based on either class or functionality) towards the `reference` section of the [`pkgdown` webpage](http://adriaandokter.com/bioRad/reference/index.html). Currently, this is a very long list of functions.

If the information could be added to the overview, I'll prep a PR to adapt the documentation `pkgdown` webpage.

**Comment by adokter** [comment]
@stijnvanhoey you mean assigning each function to a reference section (because they are functionally related)? I added a new last column `reference section` above that I could fill out.

**Comment by stijnvanhoey** [comment]
Indeed, grouping the functions in the reference page (cfr. [waterinfo](https://inbo.github.io/wateRinfo/reference/index.html)). Grouping can be on a functional relation or on the object type the functions work. I think the table is a good starting point.

**Comment by adokter** [comment]
@stijnvanhoey I made a suggestion for grouping above

**Comment by stijnvanhoey** [comment]
Adriaan, I did a quick local test, with the following result:
![image](https://user-images.githubusercontent.com/754862/33948838-3f3dae74-e028-11e7-824a-04e2b8044549.png)

Maybe just a few questions:
* You have a category `Loading data`, but following functions, which do provide data loading functionality, are provided in other categories: `is.vpfile`, `readvp`, `read.pvol` and `is.pvolfile`. Shouldn't we group all data loaders together in a single category? 
* could we put `is.param` together with the others in the category `polar scan` instead of the separate category `polar scan parameter `?
* Is there a specific reason to have `composite` in a separate category? It acts on a `ppi`, so maybe use the category `projecting scans as a plan position indicator`?

**Comment by peterdesmet** [comment]
Will the grouping by categories be the same as the grouping into different R files, or are those 2 things unrelated?

**Comment by stijnvanhoey** [comment]
Those two things are unrelated. Structuring the functions on the pkgdown webpage need to be defined in the config yaml file of pkgdown.

**Comment by peterdesmet** [comment]
Yes, they are technically unrelated. Was just wondering if it would make sense to align them a bit?

**Comment by stijnvanhoey** [comment]
In general package building documentation, mostly 1 function for a file, eventually combined with support functions for this one. However, there is no 'rule' about this, so alignment of it could be a good idea.

**Comment by adokter** [comment]
@stijnvanhoey looks good, could you push a pull request of something like this to the repo?

Regarding your questions (sorry forgot to reply earlier):
* Shouldn't we group all data loaders together in a single category? Yes I would be fine with that. Can we mention the loaders twice, e.g. both in a general dataloader category and in a specific category?
* could we put `is.param` together with the others in the category `polar scan` instead of the separate category `polar scan parameter`? I think that's ok. 
* Is there a specific reason to have `composite` in a separate category? It acts on a `ppi`, so maybe use the category `projecting scans as a plan position indicator`? Yes that's ok
* Could we maybe also combine the plot functions of  `overlaying radar scans on a map` to the  `ppi` category? Yes that's ok

**Comment by stijnvanhoey** [comment]
Ok, thanks for the information. With this information, I think I'll be able to prepare a PR beginning of April. I'll keep you posted.

**Comment by stijnvanhoey** [comment]
@adokter concerning your question in providing the link to a function multiple times (e.g. inside the category of dataloaders and the category of a specific class): yes, this is possible. Should I do this for all data-loaders?

**Comment by stijnvanhoey** [comment]
@peterdesmet with respect to the download function, I would not export the support funcntions, which would result to:

function | remarks | new file  | reference section
--- | --- | --- | ---
url_existence |  | vp_repo.R | 
download_vp | in NAMESPACE | vp_repo.R | loading data
match_filenames | | vp_repo.R | 
retrieve_vp_paths |  | vp_repo.R |

**Comment by peterdesmet** [comment]
Agree to hide helper functions, but would have to verify which ones are helper. E.g. I have used retrieve_vp_paths (without downloading).

Also, for filename: these functions also work for local files, so not sure to use _repo in name. I don’t know what name convention we have for the other files, but vp_files or get_vp_files seems more appropriate.

**Comment by adokter** [comment]
@stijnvanhoey "providing the link to a function multiple times (e.g. inside the category of dataloaders and the category of a specific class): yes, this is possible. Should I do this for all data-loaders?" Yes, I think this could be helpful for users, so if it's easy please go ahead

**Comment by adokter** [comment]
closed by commit https://github.com/adokter/bioRad/commit/8b043c5d55ef998d74dbead7d3ef0dd632464cf9
