### ISSUE TITLE
R-CMD-CHECK github action fails

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#507]
the `install_deps()` in the action causes rgdal to be installed as a source package (because latest version is only available as source and not as binary)

Possible solution is forcing rgdal to install as a binary package on MacOS

**Comment by peterdesmet** [comment]
Solved in 480d079f3188c274b740edac4cb5af7aafa69409, which adds a setting to use binary if source is not available `options("pkgType" = "binary")`.

I didn't know how to set this setting in the latest version of `use_github_action_check_standard()`, which uses:

```
- uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck
```

Would be interesting to try again once the binary for gdal is available, but for now it works. Now, need to look into #508.

**Comment by adokter** [comment]
@peterdesmet seems this solution broke on Linux, probably after a new release of some packages:
```
Run options("pkgType" = "binary") # See https://github.com/r-lib/actions/issues/141#issuecomment-664390398
tibble  (3.1.6 -> 3.1.7) [CRAN]
ggplot2 (3.3.5 -> 3.3.6) [CRAN]
Installing 2 packages: tibble, ggplot2
Error: Error in i.p(...) : type 'binary' is not supported on this platform
```

**Comment by peterdesmet** [comment]
So we're stuck between:

## Old R-CMD-Check

Previously used GitHub Action for R-CMD-Check where we added `options("pkgType" = "binary")` in https://github.com/adokter/bioRad/commit/480d079f3188c274b740edac4cb5af7aafa69409 to fix a Mac OS X issue, but which **fails on Linux** now: https://github.com/adokter/bioRad/runs/6304083595?check_suite_focus=true

```
Run options("pkgType" = "binary") # See https://github.com/r-lib/actions/issues/141#issuecomment-664390398
tibble  (3.1.6 -> 3.1.7) [CRAN]
ggplot2 (3.3.5 -> 3.3.6) [CRAN]
httr    (1.4.2 -> 1.4.3) [CRAN]
Installing 3 packages: tibble, ggplot2, httr
Error: Error in i.p(...) : type 'binary' is not supported on this platform
```

## New R-CMD-Check

Default GitHub Action as written by `usethis::use_github_action_check_standard()`. This removes our `options("pkgType" = "binary")` setting and runs fine on Linux, but brings back the **issue for Mac**: https://github.com/adokter/bioRad/runs/6304083470?check_suite_focus=true

```
x Failed to build source package 'rgdal' 
```

**Comment by peterdesmet** [comment]
I'm tempted to use the latest new action, because:

- It does not rely on a hack
- It supports two Linux versions
- The issue is with one package only `rgdal` rather than a setting we added
- We can disable Mac build

@adokter ?

**Comment by adokter** [comment]
ok sounds good, the rgdal will probably resolve itself, and ... it is a package we will have to move away from before 2023 when it's being retired.
