### ISSUE TITLE
verify if pkgdown github action is set up correctly

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#509]
Recent pkgdown runs do not complete, @peterdesmet does this require an edit to the pkgdown.yaml file, like the other actions you fixed recently?

https://github.com/adokter/bioRad/actions/workflows/pkgdown.yaml

**Comment by peterdesmet** [comment]
I have updated this at https://github.com/adokter/bioRad/commit/d85548cd8d457511270ca4c006f68bd3bbdf6ab1

This action should only run on builds to master, is that what you have tested?

**Comment by adokter** [comment]
Ok good, no haven't tested because it requires a push to master. I always build documentation with `pkgdown::build_site(run_dont_run=T)`, which also executes the dont run code blocks of the examples. That won't work with github actions. @peterdesmet could you remind me how we solved that, should I manually copy the docs folder to the root of the gh-pages branch?

**Comment by peterdesmet** [comment]
Why do we set dontrun on the examples if we want to include them in the website anyway?

**Comment by peterdesmet** [comment]
And yes, manually copying to gh-pages would be a hack you can use.

**Comment by adokter** [comment]
> Why do we set dontrun on the examples if we want to include them in the website anyway?

Because they depend on Docker-enabled code. Even when we deprecate Docker in the near future, likely we still have to build the documentation with run_dont_run=T, because certain functions of the package will rely on C libraries that won't be available on the CRAN servers
