### ISSUE TITLE
Add funder information

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#514]
@adokter would it be ok to add funder information to bioRad (cf. https://docs.ropensci.org/frictionless/authors.html)?

Funders:
- LifeWatch Belgium (my work)
- GloBAM (my work + Anders)
- ...

**Comment by peterdesmet** [comment]
Yeah, I guess that might become quite complex. Fine for me if we don't.

**Comment by bart1** [comment]
Maybe its an option to put it in the readme.md as there is more space there?
