### ISSUE TITLE
The meaning of data in the sample data 'volume.h'?

### ISSUE THREAD

**Issue by GStarmin** [adokter/bioRad#515]
what is the meaning of data in the sample data volume.h?it divide into three groups,I konw the three groups(dataset1-dataset3) stand for three elevangle scan,but what is the  meaning of  its subgroups(data1-data5)?

**Comment by bart1** [comment]
The subgroups refer to the different parameters/attributes that have been measured (e.g.DBZ VRAD). If this answers your question please close the issue
