### ISSUE TITLE
invalid cross-device link

### ISSUE THREAD

**Issue by dylanosterhaus** [adokter/bioRad#535]
https://github.com/adokter/bioRad/blob/341120fab269f65511c3a396a7ef0ab681783556/R/calculate_vp.R#L379

file.rename() creates an issue (new file fails to write) if the temporary file that is created is not on the same file system (or partition) as the location of the output file. Fix would be to use file.copy() in place of file.rename() and then file.remove() to remove the tmp file.

**Comment by adokter** [comment]
thanks @dylanosterhaus, fixed by https://github.com/adokter/bioRad/commit/442cc73ecdb192bda6e77c40ce185ab7d8456ae3
