### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [adokter/bioRad#545]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by adokter** [comment]
Thanks @rsbivand for the heads up, updating all our spatial libraries is at the top of our to-do list for 203

**Comment by rsbivand** [comment]
This package has strong dependence on at least one of `rgdal`, `rgeos` or `maptools`, but does not seem to use any functionality in code. The usage may have been in `raster`, which now uses `terra` instead, or may be in examples or vignettes. Please move all use of `rgdal`, `rgeos` or `maptools` to Suggests: and protect any use against these packages not being present. The packages will be archived in October 2023. See https://r-spatial.org/r/2022/12/14/evolution2.html and https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1.

**Comment by adokter** [comment]
@rsbivand thanks, we will move this up in priority. Do you have plans for maptools::crepuscule() to be migrated to a different package? If not, would it be ok if we integrate that piece of code into bioRad under the GPL license used by maptools? Or would you recommend a different option?

**Comment by rsbivand** [comment]
That would of course be fine. I took the functions out as https://github.com/rsbivand/sunMaptools in connection with contacts with other package maintainers:

 packages `birdscanR` https://github.com/BirdScanCommunity/birdscanR/issues/34 `EMbC` `FLightR` https://github.com/eldarrak/FLightR/issues/24 `incR` https://github.com/PabloCapilla/incR/issues/3 `PWFSLSmoke` https://github.com/MazamaScience/PWFSLSmoke/issues/124 `shadow` https://github.com/michaeldorman/shadow/issues/7 `StreamMetabolism` https://github.com/ssefick/StreamMetabolism/issues/2.

**Comment by iskandari** [comment]
Add `suntools` package as a dependency once it is published on CRAN

**Comment by rsbivand** [comment]
CRAN bioRad_0.6.2.tar.gz fails CMD check with `_R_CHECK_SUGGESTS_ONLY_=true` and  forthcoming `sp` 2.0-0; adding `sf` to Suggests: remedies. I couldn't test properly with your Github HEAD which has `sf` because I don't have `vol2birdR`. `sp` 2.0-0 is coming during June.
