### ISSUE TITLE
fix for undefined symbols:

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#552]
To prevent undefined symbol notes on CRAN:

Add:
```
#' @importFrom rlang .data
```

then reference symbol as `.data$symbolname` instead of `symbolname`

see https://github.com/birdflow-science/BirdFlowR/blob/5f88985816de87bceb1d52effc4be31e78fadf22/R/route.R#L27

**Comment by PietrH** [comment]
Example: 

```
checking R code for possible problems ... [46s/59s] NOTE
  download_pvolfiles: no visible binding for global variable ‘Key’
    (/Users/runner/work/bioRad/bioRad/check/bioRad.Rcheck/00_pkg_src/bioRad/R/download_pvolfiles.R:122)
  Undefined global functions or variables:
    Key
```

in: https://github.com/adokter/bioRad/actions/runs/4993792677/jobs/8943417902

I think this is the only place? 

Reference: https://www.tidyverse.org/blog/2022/10/tidyselect-1-2-0/#using-data-inside-selections
