### ISSUE TITLE
Create `as.vpts()` function

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#555]
It is currently possible to convert a `vpts` object to a dataframe with `as.data.frame()`. The reverse is not possible, i.e. when you have a dataframe with vpts data, you cannot create a `vpts` object (to plot or use for other functions).

In the short term, it would be good to have such a function `create_vpts(df)`. This function could then also be used by the new `read_vpts()` function (#551).

In the longer term, `vpts` objects should become data frames (rather than currently lists), so it is easier to use e.g. `dplyr::filter()` and import data from vpts csv without having to convert them to objects.

**Comment by bart1** [comment]
Quickly tagging @jedgroev as he might be intrested here

**Comment by adokter** [comment]
included in #590
