### ISSUE TITLE
`vol2birdR` as a suggested package

### ISSUE THREAD

**Issue by bart1** [adokter/bioRad#557]
To reduce the dependency tree it might make sense to move `vol2birdR` to suggested packages. As far as I see it is only important for `calculate_vp`. With check installed it is easy enough to check if it is installed see: https://gitlab.com/bartk/move2/-/blob/main/R/movebank_credentials.R#L29 . It would make installing the package easier. And the checks are quickly done with: https://rlang.r-lib.org/reference/is_installed.html

**Comment by bart1** [comment]
This would currently swap around the dependency of `rlang` and `vol2birdR` but the former is already installed as it is a dependency of `tidyr`

**Comment by adokter** [comment]
Currently there is a dependency on vol2birdR for `calculate_vp()`, `nexrad_to_odim()`, `read_pvolfile()` and `apply_mistnet()`.

**Comment by bart1** [comment]
Ah that is a bit more then I thought, I thought `read_pvolfile` would only need `rhdf5`, or is it needed for nextrad files? If you want I can still make the change as there are still a lot of sensible uses of the package without these functions

**Comment by adokter** [comment]
yes, it's needed to read nexrad files, and iris files. I'm inclined to keep vol2birdR as a required dependency, as you really gut a lot of it without that functionality (it's not just those 4 functions, without them you can't do any spatial analyses within the radar domain, or plot the raw sweep data)

**Comment by bart1** [comment]
Maybe it depends on workflows, I would still be able to load odim files directly and read vpts objects from the database ;). I guess some of my docker containers would be leaner without vol2birdR. but either way likely works
