### ISSUE TITLE
some functions in NAMESPACE not shown in pkgdown webpage

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#56]
For example `is.vpts` and `dim.vpts` are missing, while `is.ppi` and `dim.ppi` do show up correctly.

**Comment by stijnvanhoey** [comment]
I checked all NAMESPACE functions and the same problem arises for `is.vplist`. What's happening is the wrong rendering towards pkgdown when having the `[.vpts` or `[.vplist` redirected `@rdname` to the summary. On the page itself, it get rendered:
![image](https://user-images.githubusercontent.com/754862/37062176-fd14b0f6-2195-11e8-8e21-da477bcdaa46.png)
but as it is interpreted as a single code block instead enlisting of methods, the differentiation is not taken into account to the overview. I assume for now this is a pkgdown issue we should check.

I first thought to make the `vpts` similar to `ppi`, but actually I do think that for `[.ppi` the `@rdname` [towards `ppi` function](https://github.com/adokter/bioRad/blob/master/R/bioRad.ppi.R#L415) should rather be the [link to the `summary.ppi`](https://github.com/adokter/bioRad/blob/master/R/bioRad.ppi.R#L873) as it is with `vpts` and `vplist`. @adokter, does this make sense? Doing so is off course causing the removal of `is.ppi` and `dim.ppi` from the overview as well. 

One solution would be to not use the `@rdname`, but providing separate pages for each of the functions.

**Comment by stijnvanhoey** [comment]
By providing a separate page for the `[.ppi`, keeping the others (`summary`, `dim` and `is.*`) grouped, we actually have a solution that renders:
- the overview
![image](https://user-images.githubusercontent.com/754862/37063142-ceea62cc-2198-11e8-954e-f34275ca6d1a.png)
- combination of the ref of `ppi`
![image](https://user-images.githubusercontent.com/754862/37063192-e40854c0-2198-11e8-811e-bbe4f364bcda.png)
- the separate docstring for the subset (I now quickly added `subset ppi` to roxygen header)
![image](https://user-images.githubusercontent.com/754862/37063215-f6756b16-2198-11e8-9317-bd0a41fd8452.png)

Would this be an option for `vp`, `vplist` and `ppi`?

**Comment by adokter** [comment]
@stijnvanhoey Thanks, yes I think an extra page for the subsetting isn't that bad, I mainly care about having all the functionality documented. So please go ahead as you suggest
