### ISSUE TITLE
Adding installation instructions about bionconductor dependency "rhdf5"

### ISSUE THREAD

**Issue by mbelotti99** [adokter/bioRad#560]
I noticed that the `bioRad` installation on Ubuntu 22.04.2 (R version 4.3.0) raised an exit status error when I first tried to install it because I didn't have the `rhdf5` package. This package is not installed through the typical `install.packages()` route. It's in the Bioconductor repository, so needs to be installed through there ([see instructions](https://www.bioconductor.org/packages/release/bioc/html/rhdf5.html)).

My question: would this be something worth mentioning in the Installation instructions?

**Comment by adokter** [comment]
Hi @mbelotti99, do you also experience this issue when installing the latest dev version? You can test it out by first removing bioRad and rhdf5 with `remove.packages(c("bioRad","rhdf5")` and then install the dev version with `devtools::install_github("adokter/bioRad")`

**Comment by mbelotti99** [comment]
Thanks, @adokter! I realize now that this is issue is solved in the development version.
