### ISSUE TITLE
warnings and errors appear in the documentation

### ISSUE THREAD

**Issue by baptischmi** [adokter/bioRad#562]
Errors and warnings appear in the *'\dontrun'* section, e.g.:

https://adriaandokter.com/bioRad/reference/example_scan

https://adriaandokter.com/bioRad/reference/example_vp

https://adriaandokter.com/bioRad/reference/example_vpts.html

**Comment by iskandari** [comment]
Remove dontrun blocks that were used when Docker was still required

**Comment by adokter** [comment]
closed by #598
