### ISSUE TITLE
Making `aws.s3` suggested

### ISSUE THREAD

**Issue by bart1** [adokter/bioRad#583]
It would be nice to make `aws.s3` suggested. It adds quite a few dependencies. In total 11 other package need to be installed because of the direct import of `aws.s3`. Currently only `download_pvolfiles` will be affected. But I guess the new alternative to `download_vpfiles`/`list_vp_files` will also be affected @PietrH ? I'm not sure how much lighter `httr` is but I guess to really cut dependencies we would  to not introduce that new import.

**Comment by bart1** [comment]
It seems `httr` on itself adds at least 5 unique dependencies

**Comment by PietrH** [comment]
Indeed `list_vp_files_aloft()` will ble affected, `httr` is a much more common package to have installed already, as it's really a wrapper for curl. I've just noticed [httr2](https://httr2.r-lib.org/) is now recommended. 

With this in mind I would still prefer to stick to `aws.s3` specifically for `aws.s3::get_bucket_df()` which seems to use a single request to list bucket contents , while my `httr` alternative takes a lot more requests and is thus much slower even when parallelized. 

I suppose I could have a go at looking how `aws.s3::get_bucket_df()` works. 

---
There currently are no plans for a `download_vp_files_aloft()`, we might include a convenience function to download a list of urls as provided by `list_vp_files_aloft()`, and that function would be likely to use `httr`/`httr2` anyway. But that is still to be discussed.

**Comment by bart1** [comment]
I would suggest it's ok to make `aws.s3` suggested for these functions and have to install it (with a simple yes to `rlang::check_installed`) when using them? Others agree?

**Comment by PietrH** [comment]
Would that mean that tests for functions using `aws.s3` would not run in CI?

**Comment by bart1** [comment]
It would still run, as suggested packages are installed for testing
