### ISSUE TITLE
Go through printing/messaging statements

### ISSUE THREAD

**Issue by bart1** [adokter/bioRad#585]
I noticed in a few places `cat` was used to print messages, its preferable to use `message`: https://stackoverflow.com/questions/36699272/why-is-message-a-better-choice-than-print-in-r-for-writing-a-package

It might be good to go through the package and see where what printing is used. This might also help to make the testing less verbose in the long run

**Comment by PietrH** [comment]
I think this is a good idea, also because this will allow users to silence these messages in `knitr` or using `supressMessages()`

[reference](https://stackoverflow.com/a/36700294)

**Comment by adokter** [comment]
Only found cat statements in download_basemap, which I have removed in https://github.com/adokter/bioRad/commit/0aba47b7596a851b716424c7324c1393568bbdaf
