### ISSUE TITLE
check error messages in tests

### ISSUE THREAD

**Issue by PietrH** [adokter/bioRad#593]
While working on #558, which is a precursor to fixing #97. I came across some tests that use `testthat::expect_error()` with no value for `regexp`, which will mean the test will pass on any error. 

**1) It would be nice to increase test robustness by adding explicit messages for `testthat::expect_error()` to match against**

But I also came across `testthat::expect_error()` expectations that used `fixed = TRUE` without a value for `regexp`, which prompts a warning but also introduces a risk of some bugs not being caught. Same goes for using `testthat::expect_error(regexp = NA, fixed = TRUE)` instead of `testthat::expect_no_error()`

**2) I propose never using `fixed = TRUE` or `regexp = NA` in `testthat::expect_error()` to increase test robustness**

In both cases tests will pass in the current state, but behaviour might not be entirely as we intended while writing the tests and we might miss future bugs even though the line is covered as reported by `covr`.

I'm already make some changes towards this in #558, but this is important to keep in mind for future review and efforts to increase test coverage towards #148. 

---

An example of behaviour we want to avoid:

```R
date_min <- as.POSIXct("2016-10-02 20:00", tz = "UTC")
date_max <- as.POSIXct("2016-10-02 20:05", tz = "UTC")
radars <- "KBBX"
directory <- tempdir()
overwrite <- TRUE

download_pvolfiles(c(date_min, date_max), date_max, radars, directory, overwrite)
```

Results in the error: 

>Error: assert_that: length of assertion is not 1

Which is probably not the intention, while the test passes because: 

`expect_error(download_pvolfiles(c(date_min, date_max), date_max, radars, directory, overwrite))` is `TRUE`

from `test-download_pvolfiles.R
`
Another one:

``` R
expect_error(download_pvolfiles(as.POSIXct("2016-10-02 23:55", tz = "UTC"),
    as.POSIXct("2016-10-03 00:07", tz = "UTC"), radars, directory, overwrite), NA, fixed = TRUE)

```

Which passes, but doesn't return an error. A warning is returned within testthat flows for passing `fixed = TRUE` which isn't used. In this case we want to use `expect_no_error()` instead so it's clear to the reader that we are in fact, not expecting an error.

**Comment by peterdesmet** [comment]
Well spotted. Can you give an example on how you would fix it? Literal expected error messages in the tests?

**Comment by PietrH** [comment]
Literal expected error messages seem the safest to me. Here is a file example: https://github.com/adokter/bioRad/blob/fafab100747dddf89bf6869be079abb7f7243af4/tests/testthat/test-download_pvolfiles.R

And here is my solution for the example in the first post:

``` R
expect_error(
    download_pvolfiles(c(date_min, date_max),
                       date_max,
                       radars,
                       directory,
                       overwrite),
    regexp = "Only one `date_min` should be provided.",
    fixed = TRUE
  )
  ```
  Note that in this particular case the function itself was not providing a good error message for more than one `date_min`, so I added an `assert_that() `statement as well:
  
  ```R
    # Stop if provided more than one date for min or max
  assertthat::assert_that(length(date_min) == 1,
                          msg = "Only one `date_min` should be provided.")              
```

**Comment by PietrH** [comment]
I've made improvements towards this in #588, I don't think there any more empty `regexp` arguments in tests, but I'm not 100% certain. For now, I think merging #588 can close this issue.
