### ISSUE TITLE
bioRad 0.7.1 release

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#599]
- [x] address any current [CRAN check issues](https://cran.r-project.org/web/checks/check_results_bioRad.html)
- [x] review and update authorship in DESCRIPTION
- [x] start cran_release branch
- [x] create bioRad 0.7.1 release PR from cran_release branch
- [x] bump version to 0.7.1 in DESCRIPTION
- [x] rebuild readme.md with `devtools::build_readme()` 
- [x] check `devtools::spellcheck()`
- [x] check that `devtools::check(cran = TRUE)` passes
- [x] check that github builds pass (triggered by PR)
- [x] update NEWS.md, describing all changes and new features
- [x] update cran-comments.md
- [x] update codemeta.json with `codemetar::write_codemeta()`
- [x] check that `devtools::check_rhub()` passes
- [x] check that `devtools::check_win_release()` passes
- [x] check that `devtools::check_mac_release()` passes
- [x] check that `devtools::check_win_devel()` passes
- [x] build pkgdown website for 0.7.1 with `devtools::build_site(run_dont_run=TRUE)`
- [x] submit to CRAN with `devtools::release()`
- [x] confirm CRAN submission email (Adriaan)
- [x] receive confirmation of release on CRAN
- [x] merge bioRad 0.7.1 PR into master
- [x] Tag release 0.7.1 on master branch
- [x] Create 0.7.1 release on Github, listing the changes from NEWS.md and linking to closed issues of 0.7.1 milestone
- [x] check that github release triggered Zenodo archive
- [ ] start new development version 0.7.1.9000 on develop branch from master (update version in DESCRIPTION). See [here](https://github.com/adokter/bioRad/pull/598#discussion_r1223097639), we will use 9000 to indicate development (and not increment it)
- [x] build and publish development website

**Comment by bart1** [comment]
@adokter & @iskandari  please notice cran submissions are currently not functioning see the message on the main page: https://cran.r-project.org/ (I got bitten by this for `move2`). I got a mail response that I should retry on Monday.

**Comment by adokter** [comment]
@peterdesmet @iskandari this step used to be necessary to override `\dontrun{}` blocks in examples:

- [ ] re-build pkgdown website for 0.7.1 with `devtools::build_site(run_dont_run=TRUE)`, and manually copy over updated files to gh-pages branch (to override github action that generates website with `devtools::build_site(run_dont_run=FALSE)`.

These blocks have now been replaced with `\donttest{}` and the pkgdown website now builds as expected. This does mean the Github action automatically downloads the mistnet model and libraries, about 700 Mb total. Is this large data volume problematic in any way, could we reach certain Github limits?

**Comment by adokter** [comment]
Thanks Peter, let's move to a release protocol using one X.X.X.9000 dev version, updated the protocol above.
