### ISSUE TITLE
Recursive issue plot_ppi.R

### ISSUE THREAD

**Issue by plieper** [adokter/bioRad#6]
plot.colours is twice specified, causing a recursive-problem.

It's first specified in [line 75](https://github.com/adokter/birdRad/blob/master/R/plot_ppi.R#L75), and then again in [line 177](https://github.com/adokter/birdRad/blob/master/R/plot_ppi.R#L177), causing trouble when you want to execute [lines 182](https://github.com/adokter/birdRad/blob/master/R/plot_ppi.R#L182) and [183](https://github.com/adokter/birdRad/blob/master/R/plot_ppi.R#L183).

Changing the name of plot.colours in [line 75](https://github.com/adokter/birdRad/blob/master/R/plot_ppi.R#L75) and accordingly in [line 177](https://github.com/adokter/birdRad/blob/master/R/plot_ppi.R#L177) solves the problem.

**Comment by adokter** [comment]
function is obsolete
