### ISSUE TITLE
Abnormal results when applying MistNet segmentation to C-Band weather radar data

### ISSUE THREAD

**Issue by fidele07** [adokter/bioRad#605]
I am currently working on applying MistNet segmentation to weather radar data obtained from a C-Band radar. However, during the plotting process, I encountered abnormal results where approximately half of the data appears to be masked. I am seeking assistance in resolving this issue.

To better understand the problem, I have uploaded a sample dataset to Google Drive. You can access the sample data using the following link: [Sample Data]  https://drive.google.com/drive/folders/1yj-lROL6jW3xp9Qylcrdx6iRpMSjz6lW?usp=drive_link

 Any guidance, suggestions, or solutions regarding this problem would be greatly appreciated.

Thank you in advance for your time and assistance.

![Biology](https://github.com/adokter/bioRad/assets/86002804/d34cb87e-70df-42b4-a166-ae027e124735)
![cell](https://github.com/adokter/bioRad/assets/86002804/6c0f1cbc-c675-46f7-b14d-f5b61f59dd0d)
 Thank you

**Comment by adokter** [comment]
Hi @fidele07, I believe there are some general issues with your file, it doesn't seem to be in a proper format, which may have to do with how you decoded your radar format to ODIM hdf5.

```
# read polar volume:
pvol=read_pvolfile("~/Downloads/odim.20201112_003009.000_to_20201112_003341.000_ARC_RADAR_SUR.h5")
# extract 0.5 degree elevation scan:
scan = get_scan(pvol,.5)
# plot the scan:
plot(scan)
```
This plot shows the file contains data only at a few azimuths, which can't be correct. Therefore I think this is primarily a problem with how your file was converted to ODIM h5 format.

![image](https://github.com/adokter/bioRad/assets/8268415/6abbbbb6-02b7-4844-acb7-a9d3d37c1874)
