### ISSUE TITLE
enable VPTS CSV format for calculate_vp()

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#607]
Currently `calculate_vp()` still writes an hdf5 file when requesting a csv file:
```
pvolfile <- system.file("extdata", "volume.h5", package = "bioRad")
calculate_vp(pvolfile, vpfile="~/test.csv")
```
This is because profile file is initialized as a tempfile here without a csv extension:
https://github.com/adokter/bioRad/blob/528840ff05a1e295ad14014323aa5f416c32ea90/R/calculate_vp.R#L339

when user requests a csv file in `vpfile` argument, this tempfile should be initialized as `tempfile(fileext = ".csv")`, such that vol2birdR will generate a csv file as expected.

`calculate_vp()` also reads the generated profile. When csv output is requested, this read line should also be updated:
https://github.com/adokter/bioRad/blob/528840ff05a1e295ad14014323aa5f416c32ea90/R/calculate_vp.R#L391
Now using `read_vpfiles()` which expects ODIM H5, should change to `read_vpts()` which accepts both csv and ODIM H5

Describe new csv format in calculate_vp documentation.

**Comment by iskandari** [comment]
Resolved in #590 7d104780bcbf6b3f927396ecedf708d8d2507fcf
