### ISSUE TITLE
units of xlim and ylim in map.ppi?

### ISSUE THREAD

**Issue by plieper** [adokter/bioRad#61]
Probably the units of `xlim` and `ylim` in the function `map.ppi` are longitude and latitude, it could be useful to add them to the description?

`xlim	  : range of longitude values to plot`
`ylim	  : range of latitude values to plot`

**Comment by adokter** [comment]
Closed by commit https://github.com/adokter/bioRad/commit/5ac4129036c6837a7df84e7246d3d161ffcfd3de
