### ISSUE TITLE
CRAN check failures

### ISSUE THREAD

**Issue by rsbivand** [adokter/bioRad#638]
@adokter I think new errors that I see in reverse dependency checks for sp, and CRAN checks https://cran.r-project.org/web/checks/check_results_bioRad.html come from `download_basemap()` and probably `source = "stamen"`. I recall seeing that "stamen" may cease to be available (https://maps.stamen.com/stadia-partnership/). This is hard to reproduce, as interactive running of the Rmd document doesn't fail for me, nor do all CMD check runs. This feels like an URL redirection delay that sometimes kicks in and other times doesn't.

**Comment by adokter** [comment]
See also https://github.com/dkahle/ggmap/pull/351

**Comment by adokter** [comment]
closed by #639, migrating from ggmap to ggspatial
