### ISSUE TITLE
fix default refractive index of water in eta_to_dbz() and dbz_to_eta()

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#642]
Currently parameter `K = 0.93` as default, however for water the correct value should be `sqrt(0.93)` at both S-band and C-band

Affected functions using `eta_to_dbz()` or `dbz_to_eta()`
- `read_cajun()`
- `integrate_to_ppi()`

The effect of the change in default is that bird densities `dens` and `eta` (and their height_integrated equivalents VID, VIR) in the output of `integrate_to_ppi()` will be a factor 1.075269 (7%) higher going forward. In `read_cajun()` the values of fields dbz and DBZH will be lower by an equivalent small amount.

**Comment by bart1** [comment]
Does this not affect `integrate_profile` as densities are calculated there as well or is that already correctly done in vol2bird?

**Comment by adokter** [comment]
Right, does not effect `integrate_profile()`, which doesn't use the `eta_to_dbz()` function.

**Comment by bart1** [comment]
Ok thx I just thought I would check as there conversions between dbzh and densties are are also made

**Comment by adokter** [comment]
closed by #643
