### ISSUE TITLE
download_basemap from Stamen no longer working

### ISSUE THREAD

**Issue by ohueppop** [adokter/bioRad#644]
Trying to download a basemap from Stamen by bm <- download_basemap(ppi) results in error "Could not resolve host: tile.stamen.com".
The reason is the recent Stamen migration to Stadia Maps (see  https://github.com/dkahle/ggmap/pull/351).
Any ideas how to solve this?

**Comment by iskandari** [comment]
@ohueppop in the latest release we switched to [ggspatial](https://github.com/paleolimbot/ggspatial) for basemaps as ggmap now [requires API keys](https://github.com/dkahle/ggmap/pull/351) to access Stamen maps.  The basemap download now happens on the fly:

```r
ppi <- project_as_ppi(example_scan)
basemap <- rosm::osm.types()[1]
map(ppi, map = basemap, param = "VRADH")
```

the basemap options from [rosm](https://github.com/paleolimbot/rosm)  are:

```r
 rosm::osm.types()
 [1] "osm"                    "opencycle"             
 [3] "hotstyle"               "loviniahike"           
 [5] "loviniacycle"           "stamenbw"              
 [7] "stamenwatercolor"       "osmtransport"          
 [9] "thunderforestlandscape" "thunderforestoutdoors" 
[11] "cartodark"              "cartolight" 
```


For a full example:
```r
?map.ppi
```

**Comment by ohueppop** [comment]
Thank you @iskandari. This works perfectly with the latest release. However, I regret that the nice old Stamen maps (e.g. those without labels) can no longer be used and now require an API key.
