### ISSUE TITLE
`download_vpfiles()` currently broken

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#648]
https://lw-enram.s3-eu-west-1.amazonaws.com no longer exists, so the function `download_vpfiles()` is currently broken:

``` r
library(bioRad)
#> Welcome to bioRad version 0.7.3
#> using vol2birdR version 0.2.2.9043 (MistNet not installed)
download_vpfiles(radars = "bejab", date_min = "2023-10-10", date_max = "2023-10-11")
#> Downloading data from https://lw-enram.s3-eu-west-1.amazonaws.com
#> bejab202310.zip: http error 404
```

<sup>Created on 2023-12-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The function should be updated to read from the `aloftdata` bucket. See also https://github.com/adokter/bioRad/issues/553 where it is suggested to rename the function to `download_vpts_aloft()` (with support for hdf5). I'm more in favour of having a generic `download_files()` function, which can be fed with a vector of URLs. That vector can be created with `list_vpts_aloft()`.

**Comment by bart1** [comment]
Note that for that later route #647 also needs to be resolved
