### ISSUE TITLE
policy violation by copy to user work directory

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#662]
`calculate_vp()` example contains a CRAN policy violation: copies to user home directory not allowed:
https://github.com/adokter/bioRad/blob/d6d0a0234c6756c6104e3dca3d4273cff3679e2e/R/calculate_vp.R#L177

**Comment by peterdesmet** [comment]
If it's just in the example, it can likely be resolved by creating a specific dir and removing it. See here for an example: https://docs.ropensci.org/frictionless/reference/write_package.html#ref-examples

**Comment by adokter** [comment]
closed by https://github.com/adokter/bioRad/commit/f27f7890ac69a686b2fabc419ec5611d1db20eb1
