### ISSUE TITLE
Output figures of roxygen examples get unique file name

### ISSUE THREAD

**Issue by stijnvanhoey** [adokter/bioRad#69]
When rebuilding the website, the output figures of the roxygen embedded examples are remade and get a unique file name using a counter (+1). As such, the figures and html are indicated as changed by git, making a cluttered history.

Current options are:
- building the website without these examples, `pkgdown::build_site(examples = FALSE)` 
- just ignoring the clutter of the history and commit the changes each rebuilt.

For the current PR in preps, I just cleaned it out to not clutter the reference section with images. When the issue is solved on the pkgdown-side, we can reintroduce the images. Using the supported `\figure` inside the roxygen could be an option as well.

**Comment by peterdesmet** [comment]
Just noticed that the counter can be set to 0 if you A) clean out the docs folder and B) start a new session before rebuilding the website. At first I thought A was enough, but you need to do B most of all to reset counter.

**Comment by peterdesmet** [comment]
Just did:

1. `pkgdown::build_site()`
2. Commit changes
3. `pkgdown::build_site()`

And the second build did not generate any new versions of the images (except as the result of a `HTTP status: 403 forbidden` in `download_basemap`). Looks like the issue has been resolved in pkgdown (I'm using 1.0.0). Closing.
