### ISSUE TITLE
Names for objects

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#80]
Issue to define which objects are available to the user and how they are named. My general thoughts:

1. Objects have short, single word names (so `pvolfile` rather than `pvol_file`)
2. Objects can be tested with a `is.name_of_object()` function.
3. Objects can be created with a `name_of_object()` function, e.g. `ppi`, `scan` (rather than `fetch_scan`), `pvol` (rather than `read.pvol`)

## Files

* [x] `pvolfile`: a hdf5 file with polar volume data. I'd argue that `pvolfile` refers to a polar volume data file in ODIM format specifically **no, is generic**
* [x] ~~`rslfile`~~: a polar volume data file in RSL format. Currently not a bioRad object, but a `is.rslfile()` function would be good. **no, don't create this object**
* [x] `vpfile`: a hdf5 file with vertical profiles of aerial migrants

## Data objects

* [x] `pvol`:  polar volume data loaded in bioRad. Consists of scans with quantities
* [x] `scan`: a scan by the radar at a certain angle. Alternative name: `sweep`
* [x] `param`: property measured by the radar for a scan (e.g. `DBZH`, `dens`) **hidden object**
* [x] ~~`quantity`~~: a property measured by the radar for a scan (e.g. `DBZH`, `dens`) or even calculated from those properties later (`mtr`). Not convinced this should be an object, but it's definitely a named parameter in functions (e.g. in `fetch`) **not an object**
* [x] `ppi`: plan position indicator for a scan. Not convinced one should be able to pass a `quantity` object to `ppi(quantity)`, but rather ppi(scan, quantity = "DBZH")
* [x] `vp`: vertical profile data loaded in bioRad. Consists of altitudes with quantities
* [x] `vpts`: a irregular or regular timeseries of vps
* [x] `vpi`: a height integrated vpts or vp. Alternative names: `vivp` (but I prefer to start with `vp`), `vphi` (but it's actually _altitude_)

## Objects to deprecate

* [x] `vplist`: a list of vp objects, should just be a regular `c(vp, vp, vp)` or `[vp, vp, vp]`

**Comment by peterdesmet** [comment]
@adokter @stijnvanhoey I think it is helpful to discuss and agree on these first, because it affects #51

**Comment by adokter** [comment]
Hi @peterdesmet, thanks for looking into this, some thoughts/comments:

## Files
* not really in favour of `rslfile` and `is.rslfile` functions. RSL is a C library that reads already many different radar formats (in theory, I've only tested NEXRAD).
* I prefer referring only to `pvolfile` and `vpfile`, optionally a function that tells you what kind of a pvolfile it is (either European ODIM, or American NEXRAD).

## Data objects
* `quantity` agree, not an object
* `param` staged for deprecation to the user, but I think we should keep it under the hood. `Param` is different from `quantity` in that it only refers to observables of the radar (so a param is always also a quantity, but a quantity may not be a param).  It is useful for keeping things structured in the underlying code. Also, certain countries send data of separate radar moments in separate files to OPERA. I therefore expect in the future we will want to provide the functionality to aggregate different params into one scan, and then multiple scans into one pvol.

**Comment by peterdesmet** [comment]
## Files

- Didn't know that, makes sense
- Perfect, let's keep `pvolfile` generic (was going back on forth on this). Knowing this:
    - `pvolfile_to_vp` (`vol2bird`) makes sense, as that function can read `nexrad` (rsl) or `odim` files
    - `pvolfile_type` (`h5ODIMobject`) should ideally be repurposed to return `ODIM`, `NEXRAD`, ...
    - `rslfile_to_pvolfile` should be renamed to `rsl_to_odim` (?)
    - Should `pvol` be able to read rsl type pvolfile?

## Data objects

- Great!
- Yeah, I already struggled a bit with that as pvol hdf5 files will refer to their quantities as params. Good to keep it under the hood, and thus not in reference/function list

Let me know if there are other things you agree/disagree with. Once settled, we can start updating stuff (starting with the reference list, to see if all of it makes sense). 😄

**Comment by adokter** [comment]
* +1 for `rslfile_to_pvolfile` to `rsl_to_odim`, or `nexrad_to_odim` as not many people know rsl.
* yes, `pvol` reads generic volume files, from both EU and USA

**Comment by peterdesmet** [comment]
1. `nexrad_to_odim` it is!
2. Perfect!

I guess the rest is settled. Are you fine with `vpi`?

**Comment by adokter** [comment]
`vpi` is definitely starting to grow on me.  Especially if we include time-integrated values (mt,rt) also in the output of `vpi()`, which is the plan, than it makes sense to drop the h, as we then integrate both in time and in height.

**Comment by peterdesmet** [comment]
Great! Closing issue.
