### ISSUE TITLE
Decide what to do with intro_ppi vignette

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#86]
There was an `intro_ppi.Rmd` vignette written by @plieper in 2017. Because it eventually contained outdated function names, its [last version](https://github.com/adokter/bioRad/blob/42ee484ce491fdbc94080991061682fcee875407/vignettes/intro_ppi.Rmd) was removed in 8f638d59b9148b6b6e37ae781088b1b1d4fd1926.

It should be checked if examples of [plot(ppi)](https://github.com/adokter/bioRad/blob/master/R/plot.ppi.R) cover what was described in the vignette.

**Comment by adokter** [comment]
@peterdesmet I've added an updated vignette that covers most of bioRad's functionality. It's adapted after course material I made earlier.

**Comment by peterdesmet** [comment]
Issue body updated to only be about `intro_ppi` vignette.

**Comment by adokter** [comment]
I think this vignette has been superseded by the newer exercises, I think we can remove it
