### ISSUE TITLE
Create release and deposit on CRAN

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#91]
- [x] Update version number to v0.4.0
- [x] Create GitHub release
- [x] Deposit on CRAN

**Comment by peterdesmet** [comment]
@adokter how are we doing on this? Paper is out but search on cran link doesn’t work.

**Comment by stijnvanhoey** [comment]
If required, I can provide support on releasing, just let me know.

**Comment by adokter** [comment]
Hi @peterdesmet @stijnvanhoey,
I've been rather swamped with other work lately, but next week after Thanksgiving I should have some time; we should publish on CRAN asap indeed. We should all have a look at https://github.com/adokter/bioRad/milestone/4 and decide which are truly critical to finish, and then publish

**Comment by peterdesmet** [comment]
We're down to 3 issues (including this one):

- #162: which you are tackling
- #131: which I am tackling (but just for `curl` + some new download functionality #173)

I've set the milestone deadline on next Friday. Let's aim to put it on CRAN by then? 💪

**Comment by adokter** [comment]
Yes let's do it! Working on #162

**Comment by adokter** [comment]
I checked all open issues and I think we are ready to go after PR #174 and PR #176 have been merged, my plate of issues is clean :)

**Comment by peterdesmet** [comment]
I think we're there. I will update `news.md`, update to `0.4.0`, render the website and create a release later this evening. @adokter then it's handover to you to get this on CRAN.

**Comment by adokter** [comment]
yoohoo

**Comment by adokter** [comment]
@peterdesmet I gave everything a final check and think we are good to go.

Note commit 0940b053e78a7ea5e363ee6e4c7085ee602c8f89 where I already bumped the version number and rebuilt the site

**Comment by peterdesmet** [comment]
Release created: https://github.com/adokter/bioRad/releases/tag/0.4.0 all yours @adokter.

**Comment by adokter** [comment]
It happened!
