### ISSUE TITLE
elangle warning in read_pvolfile

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#99]
Try:

```r
pvolfile <- system.file("extdata", "volume.h5", package = "bioRad")
read_pvolfile(pvolfile)
warnings()
```

Results in many `'FUN' is deprecated. Use 'get_angles' instead."` warnings.

Even if the function `elangle()` is removed from deprecated-bioRad, the warning is still issued. To be solved.

**Comment by adokter** [comment]
fixed by commit 28d6c3d7fa820ed88106b9d7b67a51bab571d44e
